export interface SeedQuestion {
  questionId: string;
  cert: "lpic1" | "ccna";
  category: string;
  text: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  difficulty: "beginner" | "intermediate" | "advanced";
}

// ─── 初学者向け重要基本問題 LPIC-1 (100問) + CCNA (100問) ─────────────────
export const SEED_QUESTIONS: SeedQuestion[] = [
  // ─── LPIC-1: システムアーキテクチャ (15問) ─────────────────────────────────
  {
    questionId: "q-lpic1-001",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "PC起動時にハードウェア初期化を行い、ストレージからブートローダーを呼び出す現在の標準ファームウェアはどれか？",
    options: ["UEFI", "LILO", "SysVinit", "GRUB"],
    correctIndex: 0,
    explanation: "従来のBIOSに代わり、現在の大容量ストレージやセキュアブートに対応したファームウェア規格が UEFI です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-002",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "Linuxシステム起動時にカーネルが出力したハードウェア検出メッセージを確認できるコマンドはどれか？",
    options: ["dmesg", "uname", "fdisk", "lsblk"],
    correctIndex: 0,
    explanation: "dmesg コマンドはカーネルのリングバッファに保存された起動時やハードウェア接続時のログメッセージを表示します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-003",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "LinuxシステムでPCIバスに接続されているデバイス（グラフィックボード等）の一覧を表示するコマンドはどれか？",
    options: ["lspci", "lsusb", "lsdev", "ifconfig"],
    correctIndex: 0,
    explanation: "lspci コマンドを実行することで、PCIスロットに接続された各種ハードウェアの情報を確認できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-004",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "USBバスに接続されているデバイス情報を一覧表示するコマンドはどれか？",
    options: ["lsusb", "lspci", "dmesg -u", "usb-info"],
    correctIndex: 0,
    explanation: "lsusb コマンドを実行することで、接続されているUSB機器のベンダーや製品名を確認できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-005",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "現在ロードされているカーネルモジュール（ドライバ等）の一覧を表示するコマンドはどれか？",
    options: ["lsmod", "modprobe", "insmod", "rmmod"],
    correctIndex: 0,
    explanation: "lsmod コマンドで、現在のLinuxカーネルでロードされて動作しているモジュールのリストを表示します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-006",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "依存関係を自動解決しながら、カーネルモジュールを安全に組み込み・削除できるコマンドはどれか？",
    options: ["modprobe", "insmod", "rmmod", "lsmod"],
    correctIndex: 0,
    explanation: "modprobe コマンドはモジュール間の依存関係 (/lib/modules/$(uname -r)/modules.dep) を参照して自動調整します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-007",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "Linuxの初期化プロセス（最初に起動されるプロセス PID 1）として現在広く採用されているシステム管理機能はどれか？",
    options: ["systemd", "SysVinit", "Upstart", "OpenRC"],
    correctIndex: 0,
    explanation: "現在の大半のLinuxディストリビューション（RHEL/CentOS/Ubuntu/Debian等）では systemd がPID 1として動作します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-008",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "systemd採用システムにおいて、現在のデフォルトターゲット（ランレベルに相当）を確認するコマンドはどれか？",
    options: ["systemctl get-default", "systemctl show-target", "systemd-analyze default", "systemctl list-target"],
    correctIndex: 0,
    explanation: "systemctl get-default を実行すると、graphical.target や multi-user.target などの標準起動状態が表示されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-009",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "Linuxをただちにシャットダウンし、電源をオフにする基本的なコマンドとして適切なものはどれか？",
    options: ["shutdown -h now", "reboot now", "shutdown -r now", "halt -r"],
    correctIndex: 0,
    explanation: "shutdown -h now（または poweroff）で即座にシステムの終了・電源オフを実行できます。-r は再起動です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-010",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "システムを再起動（リブート）するためのコマンドとして正しいものはどれか？",
    options: ["reboot", "shutdown -h now", "poweroff", "init 0"],
    correctIndex: 0,
    explanation: "reboot コマンド（または shutdown -r now や init 6）を実行することで、システムが安全に再起動します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-011",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "現在のシステム起動から経過している稼働時間や、平均負荷を表示するコマンドはどれか？",
    options: ["uptime", "timedatectl", "who", "uname"],
    correctIndex: 0,
    explanation: "uptime コマンドで、サーバー起動後の経過時間（稼働日数）、ログインユーザー数、ロードアベレージが表示されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-012",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "GRUB2ブートローダーのメイン設定ファイルが自動生成されて保存されるデフォルトパスとして正しいものはどれか？",
    options: ["/boot/grub/grub.cfg", "/etc/grub.conf", "/boot/grub/menu.lst", "/etc/default/grub.cfg"],
    correctIndex: 0,
    explanation: "/boot/grub/grub.cfg（UEFI等は/boot/efi配下など）がGRUB2の実設定ファイルで、通常はコマンドから自動生成されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-013",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "UEFIシステムにおいて、OS起動用のブートローダーファイル群が格納されている特殊なパーティションを何と呼ぶか？",
    options: ["ESP (EFI System Partition)", "MBR (Master Boot Record)", "SWAP Partition", "ROOT Partition"],
    correctIndex: 0,
    explanation: "UEFIはFAT32形式などでフォーマットされた ESP (EFIシステムパーティション) に保存された起動用ファイル(.efi)を呼び出します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-014",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "Linuxカーネルモジュールに関する詳細情報（作成者、ライセンス、パラメータ等）を表示するコマンドはどれか？",
    options: ["modinfo", "lsmod", "depmod", "insmod"],
    correctIndex: 0,
    explanation: "modinfo <モジュール名> でモジュールファイルのパスや説明、依存関係などのメタ情報を確認できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-015",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "Linuxシステムのシステム時刻やタイムゾーンを確認・設定するための systemd ツールはどれか？",
    options: ["timedatectl", "systemctl time", "clockctl", "datemanager"],
    correctIndex: 0,
    explanation: "timedatectl コマンドにより、日時の表示・変更、タイムゾーン設定、NTP同期状態の変更が行えます。",
    difficulty: "beginner",
  },

  // ─── LPIC-1: パッケージ管理 (15問) ──────────────────────────────────────────
  {
    questionId: "q-lpic1-016",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "Debian/Ubuntu系Linuxにおいて、オンラインリポジトリの最新パッケージ情報一覧を更新するコマンドはどれか？",
    options: ["apt update", "apt upgrade", "apt install", "apt refresh"],
    correctIndex: 0,
    explanation: "apt update でパッケージインデックスを更新し、インストール可能な最新バージョンの情報を取得します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-017",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "Debian/Ubuntu系で、インストール済みのパッケージを最新バージョンに一括アップグレードするコマンドはどれか？",
    options: ["apt upgrade", "apt update", "apt check", "dpkg -u"],
    correctIndex: 0,
    explanation: "apt upgrade により、システム上の既存パッケージを自動的に新バージョンへと更新します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-018",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "Debian/Ubuntu系で、特定のパッケージ（例: nginx）を新たにインストールするコマンドはどれか？",
    options: ["apt install nginx", "apt update nginx", "apt add nginx", "dpkg --install nginx"],
    correctIndex: 0,
    explanation: "apt install <パッケージ名> で、必要な依存パッケージと共に自動インストールします。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-019",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "Debian/Ubuntu系で、インストール済みパッケージ「nginx」を設定ファイルも含めてシステムから完全に削除するコマンドはどれか？",
    options: ["apt purge nginx", "apt remove nginx", "apt clean nginx", "dpkg -r nginx"],
    correctIndex: 0,
    explanation: "remove は設定ファイルを残しますが、purge を使用すると設定ファイルも含む完全な削除が行われます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-020",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "ダウンロード済みのDebianパッケージ (.deb) をインターネットを使わずに個別にインストールするコマンドはどれか？",
    options: ["dpkg -i package.deb", "dpkg -l package.deb", "dpkg -r package.deb", "apt check package.deb"],
    correctIndex: 0,
    explanation: "dpkg -i (-install) によりローカルにある .deb ファイルを個別にインストールできます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-021",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "Debian/Ubuntu系において、現在システムにインストールされているパッケージ一覧を表示するコマンドはどれか？",
    options: ["dpkg -l", "dpkg -i", "dpkg -s", "dpkg -r"],
    correctIndex: 0,
    explanation: "dpkg -l (list) コマンドを実行することで、インストールされているDebianパッケージのリストが一覧表示されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-022",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "特定のファイル（例: /etc/nginx/nginx.conf）がどのDebianパッケージから導入されたものか調べるコマンドはどれか？",
    options: ["dpkg -S /etc/nginx/nginx.conf", "dpkg -L /etc/nginx/nginx.conf", "dpkg -i /etc/nginx/nginx.conf", "apt search /etc/nginx/nginx.conf"],
    correctIndex: 0,
    explanation: "dpkg -S (-search) コマンドにファイルパスを指定することで、そのファイルを提供する元のパッケージ名を特定できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-023",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "RHEL/CentOS/Rocky LinuxなどのRed Hat系ディストリビューションで利用される標準的なパッケージ管理ツールはどれか？",
    options: ["dnf (または yum)", "apt", "zypper", "pacman"],
    correctIndex: 0,
    explanation: "Red Hat系Linuxでは、RPMパッケージの依存関係を自動解決するツールとして yum および後継の dnf が標準です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-024",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "Red Hat系 Linux において、ダウンロード済みの RPM ファイル (.rpm) を手動でインストールするコマンドはどれか？",
    options: ["rpm -ivh package.rpm", "rpm -e package.rpm", "rpm -qa package.rpm", "rpm -qf package.rpm"],
    correctIndex: 0,
    explanation: "-i (install)、-v (verbose:詳細表示)、-h (hash:進捗バー表示) を組み合わせた rpm -ivh が一般的です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-025",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "Red Hat系 Linux において、システムにインストールされている全ての RPM パッケージ一覧を表示するコマンドはどれか？",
    options: ["rpm -qa", "rpm -ivh", "rpm -qf", "rpm -ql"],
    correctIndex: 0,
    explanation: "rpm -qa (-query -all) コマンドでインストール済みRPMパッケージの一覧を出力できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-026",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "Red Hat系 Linux で、指定したファイル（例: /etc/passwd）がどのRPMパッケージに含まれているか調べるコマンドはどれか？",
    options: ["rpm -qf /etc/passwd", "rpm -ql /etc/passwd", "rpm -qa /etc/passwd", "rpm -qi /etc/passwd"],
    correctIndex: 0,
    explanation: "rpm -qf (-query -file) で該当するファイルが所属するRPMパッケージを検索できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-027",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "Red Hat系 Linux の dnf (yum) を用いて、パッケージ「httpd」をオンラインでインストールするコマンドはどれか？",
    options: ["dnf install httpd", "dnf update httpd", "dnf search httpd", "dnf check httpd"],
    correctIndex: 0,
    explanation: "dnf install <パッケージ名> で依存関係パッケージを解決しながら自動ダウンロード＆インストールします。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-028",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "パッケージマネージャ (apt等) で使われる「依存関係の解決」とは何を意味するか？",
    options: [
      "目的のソフトを動かすために必要な他のライブラリやツールを自動的に見つけて一緒にインストールすること",
      "ファイルのパーミッションをすべて 777 に強制設定すること",
      "古いカーネルをすべて自動で削除すること",
      "パスワードを自動的に暗号化すること",
    ],
    correctIndex: 0,
    explanation: "ソフトウェアが動作するために依存している共用ライブラリやツールを一緒に自動インストールする仕組みです。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-029",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "オープンソースソフトウェアで広く使用される「GPGキー (GnuPGキー)」をパッケージリポジトリにインポートする主な目的はどれか？",
    options: [
      "配布されているパッケージが正規の配布元から作成され、改ざんされていないか署名を検証するため",
      "インターネット通信をすべてSSL/TLS化するため",
      "ユーザーアカウントのパスワードなしログインを可能にするため",
      "ディスクアクセス速度を自動向上させるため",
    ],
    correctIndex: 0,
    explanation: "パッケージファイルが配布元によって正しく電子署名されているか確認することで改ざんやなりすましを防ぎます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-030",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "Debian/Ubuntuの apt コマンドで、ダウンロードされたローカルのキャッシュファイル (.deb) を削除してストレージ容量を空けるオプションはどれか？",
    options: ["clean", "update", "upgrade", "purge"],
    correctIndex: 0,
    explanation: "apt clean により /var/cache/apt/archives にキャッシュされたインストール用 deb ファイルをすべて削除できます。",
    difficulty: "beginner",
  },

  // ─── LPIC-1: 基本コマンド (25問) ──────────────────────────────────────────
  {
    questionId: "q-lpic1-031",
    cert: "lpic1",
    category: "基本コマンド",
    text: "カレントディレクトリ（現在自分が作業している場所）の絶対パスを表示するコマンドはどれか？",
    options: ["pwd", "cd", "ls", "which"],
    correctIndex: 0,
    explanation: "pwd (print working directory) コマンドで現在の位置を絶対パスで確認できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-032",
    cert: "lpic1",
    category: "基本コマンド",
    text: "カレントディレクトリにある全てのファイルとディレクトリを、隠しファイル (.から始まるファイル) も含めて表示するコマンドはどれか？",
    options: ["ls -a", "ls -l", "ls -h", "ls -t"],
    correctIndex: 0,
    explanation: "-a (--all) オプションを付けることで .bashrc 等の隠しファイルを含めたすべてが表示されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-033",
    cert: "lpic1",
    category: "基本コマンド",
    text: "ディレクトリを丸ごと、内部のサブディレクトリやファイルも再帰的にコピーする cp コマンドのオプションはどれか？",
    options: ["-r", "-f", "-i", "-p"],
    correctIndex: 0,
    explanation: "-r（または -R: recursive）を指定することでフォルダ構造を再帰的にコピーできます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-034",
    cert: "lpic1",
    category: "基本コマンド",
    text: "既存のファイル名「old.txt」を「new.txt」に変更する、または別ディレクトリに移動するためのコマンドはどれか？",
    options: ["mv", "cp", "rm", "rn"],
    correctIndex: 0,
    explanation: "mv (move) コマンドでファイル・ディレクトリの移動や名前の変更 (リネーム) を行います。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-035",
    cert: "lpic1",
    category: "基本コマンド",
    text: "ファイルやディレクトリを削除する基本的なコマンドはどれか？",
    options: ["rm", "del", "remove", "erase"],
    correctIndex: 0,
    explanation: "rm (remove) コマンドでファイルを削除します。ディレクトリごと消す場合は rm -r を使います。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-036",
    cert: "lpic1",
    category: "基本コマンド",
    text: "新しいディレクトリ「work」を作成するためのコマンドはどれか？",
    options: ["mkdir work", "touch work", "create work", "mkfile work"],
    correctIndex: 0,
    explanation: "mkdir (make directory) コマンドで新しいディレクトリを作成できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-037",
    cert: "lpic1",
    category: "基本コマンド",
    text: "タイムスタンプを現在の時刻に更新したり、空の新しいファイルを簡単に作成するコマンドはどれか？",
    options: ["touch", "cat", "echo", "make"],
    correctIndex: 0,
    explanation: "touch コマンドはファイルの最終更新日時を更新し、対象が存在しない場合は新規に空ファイルを作成します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-038",
    cert: "lpic1",
    category: "基本コマンド",
    text: "ファイル「sample.txt」の内容を最初から最後まで標準出力に表示する基本コマンドはどれか？",
    options: ["cat", "tac", "less", "head"],
    correctIndex: 0,
    explanation: "cat コマンドはテキストファイル全体を一気に出力します。設定の確認などで最もよく使用されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-039",
    cert: "lpic1",
    category: "基本コマンド",
    text: "長大なログファイル「syslog.txt」を、上下にスクロールしたり検索しながら閲覧できるページャーコマンドはどれか？",
    options: ["less", "cat", "head", "tail"],
    correctIndex: 0,
    explanation: "less コマンドは1画面ごとにスクロールして確認でき、/ 記号で文字列検索も可能な定番ビューアです。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-040",
    cert: "lpic1",
    category: "基本コマンド",
    text: "ファイル「data.txt」の先頭10行だけを確認するコマンドはどれか？",
    options: ["head data.txt", "tail data.txt", "top data.txt", "first data.txt"],
    correctIndex: 0,
    explanation: "head コマンドはデフォルトでファイルの先頭10行を表示します。-n オプションで行数変更が可能です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-041",
    cert: "lpic1",
    category: "基本コマンド",
    text: "ファイル「data.txt」の末尾10行だけを確認するコマンドはどれか？",
    options: ["tail data.txt", "head data.txt", "end data.txt", "last data.txt"],
    correctIndex: 0,
    explanation: "tail コマンドはファイルの最終行から10行を表示します。ログファイルの末尾確認などに使われます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-042",
    cert: "lpic1",
    category: "基本コマンド",
    text: "サーバーのログファイル「app.log」が追記されていく様子をリアルタイムに監視し続けるコマンドはどれか？",
    options: ["tail -f app.log", "head -f app.log", "cat -f app.log", "less -r app.log"],
    correctIndex: 0,
    explanation: "tail -f (-follow) を指定すると、ファイルの更新監視モードになり新しく追記されたログがリアルタイム表示されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-043",
    cert: "lpic1",
    category: "基本コマンド",
    text: "ファイル中から「ERROR」という文字列を含む行だけを検索して抽出するコマンドはどれか？",
    options: ["grep ERROR log.txt", "find ERROR log.txt", "search ERROR log.txt", "select ERROR log.txt"],
    correctIndex: 0,
    explanation: "grep コマンドにより指定した文字列やパターン（正規表現）が含まれる行を瞬時に抽出できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-044",
    cert: "lpic1",
    category: "基本コマンド",
    text: "大文字・小文字を区別せずに文字列検索を行うgrepコマンドのオプションはどれか？",
    options: ["-i", "-v", "-n", "-c"],
    correctIndex: 0,
    explanation: "-i (ignore case) オプションを指定することで、ERROR や error を区別せず一度に検索可能です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-045",
    cert: "lpic1",
    category: "基本コマンド",
    text: "ファイル「list.txt」の総行数、単語数、バイト数をカウントして表示するコマンドはどれか？",
    options: ["wc list.txt", "count list.txt", "num list.txt", "calc list.txt"],
    correctIndex: 0,
    explanation: "wc (word count) コマンドを実行すると行数・単語数・バイト数が出力されます。行数のみは -l を付けます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-046",
    cert: "lpic1",
    category: "基本コマンド",
    text: "テキストファイルの各行をアルファベット順・昇順に並べ替えて出力するコマンドはどれか？",
    options: ["sort", "uniq", "order", "arrange"],
    correctIndex: 0,
    explanation: "sort コマンドで行をアルファベット順（数値ソートは -n）に並べ替えて表示できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-047",
    cert: "lpic1",
    category: "基本コマンド",
    text: "ソートされたリストの中で、連続して重複している行を1行にまとめて出力するコマンドはどれか？",
    options: ["uniq", "sort -u", "distinct", "clean"],
    correctIndex: 0,
    explanation: "uniq コマンドは連続する重複行を排除して1行だけを出力します。通常は sort とパイプ(|)で連携して使われます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-048",
    cert: "lpic1",
    category: "基本コマンド",
    text: "カンマやタブなどの区切り文字で列（フィールド）が分割されているデータから、特定の列だけを取り出すコマンドはどれか？",
    options: ["cut", "paste", "split", "slice"],
    correctIndex: 0,
    explanation: "cut -d ',' -f 1 のようにして特定の区切り文字(-d)およびフィールド番号(-f)を抽出できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-049",
    cert: "lpic1",
    category: "基本コマンド",
    text: "指定したディレクトリ下から、ファイル名や種類・更新日時などを条件にしてファイルを検索する定番コマンドはどれか？",
    options: ["find", "locate", "whereis", "which"],
    correctIndex: 0,
    explanation: "find <検索起点パス> -name '*.log' のように指定して、条件に合致するファイルを詳細検索できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-050",
    cert: "lpic1",
    category: "基本コマンド",
    text: "前段のコマンドの出力結果を、後段のコマンドの入力へ流し込むための記法（パイプ）として使用する記号はどれか？",
    options: ["| (垂直バー)", "> (大なり)", "& (アンパサンド)", "; (セミコロン)"],
    correctIndex: 0,
    explanation: "パイプ | を使うことで ls -l | grep txt のように複数コマンドを直列につないで処理できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-051",
    cert: "lpic1",
    category: "基本コマンド",
    text: "コマンドの標準出力をファイルに「上書き保存」するリダイレクト記号はどれか？",
    options: [">", ">>", "<", "<<"],
    correctIndex: 0,
    explanation: "> でファイルに上書き保存、>> を使うとファイルの末尾への「追記」保存となります。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-052",
    cert: "lpic1",
    category: "基本コマンド",
    text: "コマンドの標準出力をファイルに「追記保存」するリダイレクト記号はどれか？",
    options: [">>", ">", "<", "|"],
    correctIndex: 0,
    explanation: ">> を使用することで、既存ファイルの末尾に新しい出力結果を継続追加します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-053",
    cert: "lpic1",
    category: "基本コマンド",
    text: "Linuxコマンドの使い方のマニュアル（公式オンラインヘルプ）を表示するコマンドはどれか？",
    options: ["man", "help", "info", "doc"],
    correctIndex: 0,
    explanation: "man <コマンド名> で詳しいマニュアル（manページ）を参照できます。終了は q キーです。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-054",
    cert: "lpic1",
    category: "基本コマンド",
    text: "実行しようとしているコマンド（例: bash）の実行バイナリファイルがある完全なパス（/usr/bin/bash等）を確認するコマンドはどれか？",
    options: ["which", "whatis", "whereis", "find"],
    correctIndex: 0,
    explanation: "which <コマンド名> で、環境変数 PATH で検索される実際の実行ファイルパスを表示できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-055",
    cert: "lpic1",
    category: "基本コマンド",
    text: "ファイルやディレクトリの所有者情報・サイズ・権限など詳細な変更タイムスタンプ情報 (atime, mtime, ctime) を表示するコマンドはどれか？",
    options: ["stat", "info", "date", "touch"],
    correctIndex: 0,
    explanation: "stat <ファイル名> でファイルのinode番号や詳細な時刻・権限メタ情報を確認できます。",
    difficulty: "beginner",
  },

  // ─── LPIC-1: デバイスとファイルシステム (15問) ───────────────────────────────
  {
    questionId: "q-lpic1-056",
    cert: "lpic1",
    category: "デバイス&ファイルシステム",
    text: "Linux起動時に自動マウントするファイルシステムやマウントポイントの構成情報が記述されているファイルはどれか？",
    options: ["/etc/fstab", "/etc/mtab", "/etc/mounts", "/etc/disks"],
    correctIndex: 0,
    explanation: "/etc/fstab はシステム起動時のファイルシステムマウント設定テーブルです。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-057",
    cert: "lpic1",
    category: "デバイス&ファイルシステム",
    text: "システム内のファイルシステムのディスク総容量と空き容量を、人間が読みやすい単位 (MB, GB等) で確認するコマンドはどれか？",
    options: ["df -h", "du -sh", "lsblk", "fdisk -l"],
    correctIndex: 0,
    explanation: "df -h (disk free human-readable) により各マウントポイントのディスク使用率を確認できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-058",
    cert: "lpic1",
    category: "デバイス&ファイルシステム",
    text: "特定のディレクトリやファイルが消費しているディスク使用量を人間が読みやすい単位で集計表示するコマンドはどれか？",
    options: ["du -sh", "df -h", "wc -c", "stat -s"],
    correctIndex: 0,
    explanation: "du -sh (disk usage summary human-readable) により、該当ディレクトリのサイズ合計を調べられます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-059",
    cert: "lpic1",
    category: "デバイス&ファイルシステム",
    text: "接続されているハードディスクやSSD等のブロックデバイス一覧を階層ツリー状に表示するコマンドはどれか？",
    options: ["lsblk", "lspci", "lsusb", "fdisk"],
    correctIndex: 0,
    explanation: "lsblk コマンドでパーティション構成やマウント状況が一目でわかるリストが出力されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-060",
    cert: "lpic1",
    category: "デバイス&ファイルシステム",
    text: "ストレージデバイス上のパーティション（例: /dev/sdb1）を、ディレクトリ（例: /mnt/data）に結合（マウント）するコマンドはどれか？",
    options: ["mount /dev/sdb1 /mnt/data", "link /dev/sdb1 /mnt/data", "attach /dev/sdb1 /mnt/data", "bind /dev/sdb1 /mnt/data"],
    correctIndex: 0,
    explanation: "mount <デバイス> <マウントポイント> により、Linuxディレクトリツリー下にディスクを接続します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-061",
    cert: "lpic1",
    category: "デバイス&ファイルシステム",
    text: "マウントされているファイルシステム（例: /mnt/data）を切り離す（アンマウントする）コマンドはどれか？",
    options: ["umount /mnt/data", "unmount /mnt/data", "dismount /mnt/data", "detach /mnt/data"],
    correctIndex: 0,
    explanation: "アンマウントするコマンド名は unmount ではなく n のない umount なので間違えないよう注意してください。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-062",
    cert: "lpic1",
    category: "デバイス&ファイルシステム",
    text: "新規パーティションに標準的な Linux 用 ext4 ファイルシステムを作成（フォーマット）するためのコマンドはどれか？",
    options: ["mkfs.ext4 /dev/sdb1", "format.ext4 /dev/sdb1", "fdisk.ext4 /dev/sdb1", "mkfs -type ext4 /dev/sdb1"],
    correctIndex: 0,
    explanation: "mkfs.ext4（または mkfs -t ext4）コマンドによりファイルシステムの初期フォーマットが完了します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-063",
    cert: "lpic1",
    category: "デバイス&ファイルシステム",
    text: "Linuxにおけるすべてのファイルやディレクトリが所属する、階層ツリーの最上位にあるルートディレクトリの記法はどれか？",
    options: ["/", "/root", "/home", "C:\\\\"],
    correctIndex: 0,
    explanation: "Linuxファイルシステムツリーの原点であるルートディレクトリはスラッシュ (/) で表記されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-064",
    cert: "lpic1",
    category: "デバイス&ファイルシステム",
    text: "Linuxファイルシステム階層標準 (FHS) において、システム管理用の設定ファイルが格納されるディレクトリはどれか？",
    options: ["/etc", "/bin", "/var", "/tmp"],
    correctIndex: 0,
    explanation: "/etc ディレクトリにはシステムのネットワークやユーザー等の主要な設定ファイルが集中しています。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-065",
    cert: "lpic1",
    category: "デバイス&ファイルシステム",
    text: "Linuxファイルシステム階層標準 (FHS) において、ログファイルやメールキューなどの変化し続けるデータが配置されるディレクトリはどれか？",
    options: ["/var", "/usr", "/opt", "/home"],
    correctIndex: 0,
    explanation: "/var (variable) ディレクトリにはシステム稼働中のログ (/var/log) などの変動データが保存されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-066",
    cert: "lpic1",
    category: "デバイス&ファイルシステム",
    text: "ファイルやパーティションに割り振られた固有識別コード「UUID (Universally Unique Identifier)」を確認できるコマンドはどれか？",
    options: ["blkid", "uuidgen", "lsid", "fdisk -u"],
    correctIndex: 0,
    explanation: "blkid コマンドで接続デバイスのUUIDやファイルシステムタイプが確認できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-067",
    cert: "lpic1",
    category: "デバイス&ファイルシステム",
    text: "MBR形式のパーティションテーブルを作成・編集する標準の対話型コマンドはどれか？",
    options: ["fdisk", "gdisk", "parted", "mkfs"],
    correctIndex: 0,
    explanation: "fdisk コマンドは古くから普及しているMBR形式パーティションテーブル編集ツールです。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-068",
    cert: "lpic1",
    category: "デバイス&ファイルシステム",
    text: "GPT (GUID Partition Table) 形式に対応した対話型パーティション作成コマンドはどれか？",
    options: ["gdisk (または parted)", "fdisk", "sfdisk", "cfdisk -m"],
    correctIndex: 0,
    explanation: "大容量2TB以上のストレージで必須となるGPT形式には gdisk または GNU parted が使用されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-069",
    cert: "lpic1",
    category: "デバイス&ファイルシステム",
    text: "メモリが不足した際に、一時的にメモリの代替領域として使用されるディスク領域（またはファイル）を何と呼ぶか？",
    options: ["スワップ領域 (Swap)", "キャッシュ領域 (Cache)", "バッファ領域 (Buffer)", "テンポラリ領域 (/tmp)"],
    correctIndex: 0,
    explanation: "Swap領域を設定しておくことで、実メモリが枯渇した際にもシステムダウンを回避して動作継続できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-070",
    cert: "lpic1",
    category: "デバイス&ファイルシステム",
    text: "作成済みのスワップパーティション（またはスワップファイル）をシステムで有効化して使用開始するコマンドはどれか？",
    options: ["swapon /dev/sdb2", "swapoff /dev/sdb2", "mkswap /dev/sdb2", "mount -t swap /dev/sdb2"],
    correctIndex: 0,
    explanation: "mkswap で領域を初期化した後、swapon コマンドで有効化します。停止は swapoff です。",
    difficulty: "beginner",
  },

  // ─── LPIC-1: シェルとスクリプト (15問) ──────────────────────────────────────────
  {
    questionId: "q-lpic1-071",
    cert: "lpic1",
    category: "シェル&スクリプト",
    text: "シェルスクリプトファイルの先頭1行目に「どのシェルで実行すべきか」を指定する記法（#!/bin/bash等）を何と呼ぶか？",
    options: ["シバン (Shebang)", "マジックコメント", "ヘッダ宣言", "シェラブル"],
    correctIndex: 0,
    explanation: "#! から始まる行をシバンと呼び、スクリプト実行インタープリターのパスをOSに指定します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-072",
    cert: "lpic1",
    category: "シェル&スクリプト",
    text: "シェルスクリプトファイル「script.sh」に所有者の実行権限 (+x) を与えて実行可能にするコマンドはどれか？",
    options: ["chmod u+x script.sh", "chown u+x script.sh", "chmod 644 script.sh", "umask +x script.sh"],
    correctIndex: 0,
    explanation: "chmod u+x（または chmod 755）によりファイルを実行可能なプログラムとして指定します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-073",
    cert: "lpic1",
    category: "シェル&スクリプト",
    text: "変数 VAL に値 'test' を代入した上で、子プロセスや他プログラムから環境変数として参照可能にするコマンドはどれか？",
    options: ["export VAL", "source VAL", "import VAL", "set VAL"],
    correctIndex: 0,
    explanation: "export コマンドで変数をエクスポートすることで、環境変数として継承されるようになります。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-074",
    cert: "lpic1",
    category: "シェル&スクリプト",
    text: "コマンドの実行履歴（ヒストリ）を一覧で確認するためのコマンドはどれか？",
    options: ["history", "log", "recent", "records"],
    correctIndex: 0,
    explanation: "history コマンドを実行すると過去に実行したコマンドのリストと番号が表示されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-075",
    cert: "lpic1",
    category: "シェル&スクリプト",
    text: "コマンドや文字列をターミナル画面に表示したり、環境変数の値を出力確認するコマンドはどれか？",
    options: ["echo", "print", "display", "show"],
    correctIndex: 0,
    explanation: "echo $USER や echo 'hello' のように記述してテキストを出力します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-076",
    cert: "lpic1",
    category: "シェル&スクリプト",
    text: "ユーザー名やパスワードの入力等、スクリプト実行中に対話的に標準入力からのキー入力を変数に読み込むコマンドはどれか？",
    options: ["read", "input", "get", "prompt"],
    correctIndex: 0,
    explanation: "read VAR と記述するとユーザーのキー入力が変数 VAR に格納されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-077",
    cert: "lpic1",
    category: "シェル&スクリプト",
    text: "直前に実行したコマンドの終了ステータス番号（成功:0、失敗:1以上）が格納されている特殊なシェル変数はどれか？",
    options: ["$?", "$!", "$$", "$0"],
    correctIndex: 0,
    explanation: "$? を参照することで、前のコマンドが正常終了したかエラーだったかをスクリプト内で判定できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-078",
    cert: "lpic1",
    category: "シェル&スクリプト",
    text: "Bash スクリプト内で、条件分岐を実行するための基本的な構文キーワードの組み合わせとして正しいものはどれか？",
    options: ["if ... then ... else ... fi", "if ... then ... else ... end", "if ... do ... else ... done", "if ... case ... esac"],
    correctIndex: 0,
    explanation: "Bashの if 文は、if, then, (else), fi（ifの逆綴り）で閉じます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-079",
    cert: "lpic1",
    category: "シェル&スクリプト",
    text: "リスト内の各項目を順番に取り出して繰り返し処理を行うBashのループ構文として正しいものはどれか？",
    options: ["for ... do ... done", "for ... start ... end", "for ... then ... fi", "while ... case ... esac"],
    correctIndex: 0,
    explanation: "for 変数 in リスト; do 処理; done の構造で繰り返し処理を行います。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-080",
    cert: "lpic1",
    category: "シェル&スクリプト",
    text: "条件式を記述してファイルの有無や文字列・数値の比較を行う test コマンドと同等の働きをする記法はどれか？",
    options: ["[ 条件式 ]", "( 条件式 )", "{ 条件式 }", "< 条件式 >"],
    correctIndex: 0,
    explanation: "if [ -f file.txt ]; then のように角括弧 [ ] を使って test 条件を評価します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-081",
    cert: "lpic1",
    category: "シェル&スクリプト",
    text: "ユーザーがログインした際、自分のホームディレクトリにあれば最初に自動で読み込まれてカスタム設定を反映するファイルはどれか？",
    options: ["~/.bash_profile (または ~/.profile)", "~/.bash_logout", "/etc/fstab", "/var/log/boot.log"],
    correctIndex: 0,
    explanation: "ログイン時に ~/.bash_profile や ~/.bashrc が読み込まれ、ユーザー独自の環境変数を適用します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-082",
    cert: "lpic1",
    category: "シェル&スクリプト",
    text: "よく使う長いコマンドに短い名前（例: alias ll='ls -la'）を付けて簡単に呼び出せるようにするコマンドはどれか？",
    options: ["alias", "short", "macro", "define"],
    correctIndex: 0,
    explanation: "alias コマンドを使うことでコマンドの短縮別名を作成できます。解除は unalias です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-083",
    cert: "lpic1",
    category: "シェル&スクリプト",
    text: "現在のシェル（またはスクリプト）自身のプロセスID (PID) が保持されている特殊変数はどれか？",
    options: ["$$", "$?", "$#", "$0"],
    correctIndex: 0,
    explanation: "$$ を参照することで自分自身の実行PIDを特定でき、一時ファイルのファイル名等に利用されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-084",
    cert: "lpic1",
    category: "シェル&スクリプト",
    text: "スクリプト実行時に渡されたコマンドライン引数の「総数」を保持する特殊変数はどれか？",
    options: ["$#", "$@", "$*", "$1"],
    correctIndex: 0,
    explanation: "$# は指定された引数の個数を返します。第一引数は $1、全引数一覧は $@ です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-085",
    cert: "lpic1",
    category: "シェル&スクリプト",
    text: "シェルの設定ファイル（例: ~/.bashrc）を現在のターミナルセッションに再読み込みして即時に反映するコマンドはどれか？",
    options: ["source ~/.bashrc (または . ~/.bashrc)", "exec ~/.bashrc", "load ~/.bashrc", "bash-reload ~/.bashrc"],
    correctIndex: 0,
    explanation: "source コマンド（ショートカット記法は ドット .）によりセッション環境に変更を反映させます。",
    difficulty: "beginner",
  },

  // ─── LPIC-1: ユーザーとセキュリティ (15問) ─────────────────────────────────────
  {
    questionId: "q-lpic1-086",
    cert: "lpic1",
    category: "ユーザー&グループ管理",
    text: "全ユーザーアカウント名、UID、ホームディレクトリ、デフォルトシェル等の基本情報が定義されているファイルはどれか？",
    options: ["/etc/passwd", "/etc/shadow", "/etc/group", "/etc/gshadow"],
    correctIndex: 0,
    explanation: "/etc/passwd に全アカウントの基本データがあり、誰でも読める状態で格納されています。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-087",
    cert: "lpic1",
    category: "ユーザー&グループ管理",
    text: "暗号化（ハッシュ化）されたパスワードやパスワードの有効期限管理情報が安全に格納されているファイルはどれか？",
    options: ["/etc/shadow", "/etc/passwd", "/etc/security", "/etc/login.defs"],
    correctIndex: 0,
    explanation: "セキュリティのため、パスワード本体は root のみが読める /etc/shadow に格納されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-088",
    cert: "lpic1",
    category: "ユーザー&グループ管理",
    text: "新しくユーザーアカウントを追加・作成するための標準コマンドはどれか？",
    options: ["useradd", "addgroup", "mkuser", "createuser"],
    correctIndex: 0,
    explanation: "useradd コマンド（またはインタラクティブな adduser）を使用してアカウントを作成します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-089",
    cert: "lpic1",
    category: "ユーザー&グループ管理",
    text: "アカウント作成と同時にユーザーのホームディレクトリも作成するための useradd コマンドのオプションはどれか？",
    options: ["-m", "-d", "-s", "-g"],
    correctIndex: 0,
    explanation: "useradd -m (--create-home) で /etc/skel の設定テンプレートをベースにホームフォルダを作ります。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-090",
    cert: "lpic1",
    category: "ユーザー&グループ管理",
    text: "自身のパスワード（または root が他ユーザーのパスワード）を変更するためのコマンドはどれか？",
    options: ["passwd", "chpasswd", "pwd-change", "userpwd"],
    correctIndex: 0,
    explanation: "passwd コマンドを実行して安全に対話形式でパスワードを変更します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-091",
    cert: "lpic1",
    category: "ユーザー&グループ管理",
    text: "既存ユーザーのログインシェル（例: /bin/bash や /bin/zsh）を変更するコマンドはどれか？",
    options: ["chsh", "chfn", "usermod", "chshell"],
    correctIndex: 0,
    explanation: "chsh (change shell) コマンドを実行してユーザーの標準ログインシェルを変更できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-092",
    cert: "lpic1",
    category: "ユーザー&グループ管理",
    text: "既存ユーザーアカウントの設定（所属グループ、ホームディレクトリ等）を変更・修正する標準コマンドはどれか？",
    options: ["usermod", "useredit", "chuser", "moduser"],
    correctIndex: 0,
    explanation: "usermod -aG group user のようにして既存ユーザーにサブグループを追加設定できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-093",
    cert: "lpic1",
    category: "ユーザー&グループ管理",
    text: "不要になったユーザーアカウントおよびそのホームディレクトリもまとめて完全にシステムから削除するコマンドはどれか？",
    options: ["userdel -r", "userdel -f", "rmuser -all", "deluser --force"],
    correctIndex: 0,
    explanation: "userdel -r (--remove) を指定することで、アカウントとホームディレクトリ・メールスプールも同時削除します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-094",
    cert: "lpic1",
    category: "ユーザー&グループ管理",
    text: "システム内のグループアカウントとそれぞれの所属メンバー情報が保存されているファイルはどれか？",
    options: ["/etc/group", "/etc/passwd", "/etc/groups", "/etc/shadow"],
    correctIndex: 0,
    explanation: "/etc/group ファイルに各グループ名、GID、所属ユーザー名一覧が記載されています。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-095",
    cert: "lpic1",
    category: "ユーザー&グループ管理",
    text: "現在のログインユーザーから別のユーザー（指定しない場合は root）のアカウントへセッションを切り替えるコマンドはどれか？",
    options: ["su", "sudo", "switch", "login-user"],
    correctIndex: 0,
    explanation: "su (switch user / substitute user) コマンドを使うと他のユーザーになり変わることができます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-096",
    cert: "lpic1",
    category: "ユーザー&グループ管理",
    text: "許可されたユーザーが自身のパスワードで一時的に管理者(root)権限で個別のコマンドを実行できるコマンドはどれか？",
    options: ["sudo", "su --admin", "runas-root", "exec-root"],
    correctIndex: 0,
    explanation: "sudo コマンドを使うことで /etc/sudoers のポリシーに基づき、rootパスワードを知らなくても安全に管理操作を行えます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-097",
    cert: "lpic1",
    category: "ユーザー&グループ管理",
    text: "sudo コマンドを使用できるユーザーや実行可能コマンド範囲を定義する設定ファイルを安全に編集するための専用コマンドはどれか？",
    options: ["visudo", "vi /etc/sudoers", "nano /etc/sudoers", "sudoedit /etc/sudo"],
    correctIndex: 0,
    explanation: "visudo コマンドを使うことで文法エラーを自動検出し、設定ミスによるロックアウト事故を防止します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-098",
    cert: "lpic1",
    category: "ユーザー&グループ管理",
    text: "新規ユーザーアカウントを作成した際に、デフォルトのファイルが自動コピーされる雛形（スケルトン）ディレクトリはどれか？",
    options: ["/etc/skel", "/etc/default/user", "/usr/share/skel", "/home/.template"],
    correctIndex: 0,
    explanation: "/etc/skel ディレクトリ内の .bashrc や .profile が、ユーザー作成時に自動でホームに配置されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-099",
    cert: "lpic1",
    category: "ユーザー&グループ管理",
    text: "現在システムに誰がログインしているのかを確認する簡単なコマンドはどれか？",
    options: ["who (または w)", "users-list", "whois", "logins"],
    correctIndex: 0,
    explanation: "who や w コマンドで現在接続中のアカウント、ログイン時間やリモートホストを確認できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-100",
    cert: "lpic1",
    category: "ユーザー&グループ管理",
    text: "新しくグループを作成するためのコマンドはどれか？",
    options: ["groupadd", "mkgroup", "addgroup", "creategroup"],
    correctIndex: 0,
    explanation: "groupadd <グループ名> により、システムに新たなグループを作成します。",
    difficulty: "beginner",
  },

  // ─── CCNA: ネットワーク基礎 (20問) ──────────────────────────────────────────
  {
    questionId: "q-ccna-001",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "国際標準化機構(ISO)が定めた、コンピュータの通信機能を7つの階層に分類した標準規格モデルはどれか？",
    options: ["OSI参照モデル", "TCP/IPモデル", "IEEE 802スタンダード", "RFC階層モデル"],
    correctIndex: 0,
    explanation: "OSI参照モデルは物理層からアプリケーション層までの7階層で通信プロセスを規格化した標準モデルです。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-002",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "OSI参照モデルにおいて、ルーターがIPアドレスを用いて通信経路の選択（ルーティング）を行うのはどのレイヤか？",
    options: ["ネットワーク層 (レイヤ3)", "データリンク層 (レイヤ2)", "トランスポート層 (レイヤ4)", "物理層 (レイヤ1)"],
    correctIndex: 0,
    explanation: "ネットワーク層（レイヤ3）はIPアドレスに基づく経路決定やパケット転送を担います。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-003",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "OSI参照モデルのデータリンク層 (レイヤ2) において、イーサネットフレームの転送に使用されるハードウェア固有のアドレスはどれか？",
    options: ["MACアドレス", "IPアドレス", "ポート番号", "UUID"],
    correctIndex: 0,
    explanation: "MACアドレスはNICなどのネットワーク機器に割り当てられた48ビットの物理アドレスです。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-004",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "TCP/IPプロトコルスイートにおけるトランスポート層のプロトコルで、信頼性の高いコネクション指向の通信を行うものはどれか？",
    options: ["TCP", "UDP", "IP", "ICMP"],
    correctIndex: 0,
    explanation: "TCP (Transmission Control Protocol) はスリーウェイハンドシェイクや再送制御を行い確実なデータ送信を実現します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-005",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "TCPと異なり接続確立手続きや再送制御を行わず、動画配信や音声通話などに利用される高速・低遅延なプロトコルはどれか？",
    options: ["UDP", "TCP", "HTTP", "ARP"],
    correctIndex: 0,
    explanation: "UDP (User Datagram Protocol) はコネクションレスで処理オーバーヘッドが小さいため高速処理に向きます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-006",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "TCP通信の開始時に、クライアントとサーバー間で通信の同期（SYN, SYN/ACK, ACK）を行い接続を確立する手順を何と呼ぶか？",
    options: ["スリーウェイハンドシェイク", "ウィンドウ制御", "フロー制御", "スライディングウィンドウ"],
    correctIndex: 0,
    explanation: "SYN → SYN/ACK → ACK の3回のパケット交換によりTCPコネクションを安全に確立します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-007",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "イーサネットで広く使用されるツイストペアケーブル（LANケーブル）について、両端の配線順序が同一で一般的な機器接続に使うケーブルはどれか？",
    options: ["ストレートケーブル", "クロスケーブル", "ロールオーバーケーブル", "同軸ケーブル"],
    correctIndex: 0,
    explanation: "PCとスイッチなどの異種デバイス接続には配線順序が同一のストレートケーブルを使用します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-008",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "Cisco機器のコンソールポートとPCのシリアルポートを物理接続して初期設定を行う際に使用する専用のケーブルはどれか？",
    options: ["コンソールケーブル (ロールオーバーケーブル)", "ストレートケーブル", "クロスケーブル", "光ファイバーケーブル"],
    correctIndex: 0,
    explanation: "Ciscoルーター等のコンソール接続にはピン配列が完全反転したロールオーバーケーブルを用います。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-009",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "MACアドレスのビット長として正しいものはどれか？",
    options: ["48ビット (6バイト)", "32ビット (4バイト)", "128ビット (16バイト)", "64ビット (8バイト)"],
    correctIndex: 0,
    explanation: "MACアドレスは前半24ビットのベンダーコード(OUI)と後半24ビットの固有番号の計48ビットで構成されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-010",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "現在のスイッチポートで一般的となっている、送信と受信を同時に並行して行う通信方式はどれか？",
    options: ["全二重通信 (フルデュプレックス)", "半二重通信 (ハーフデュプレックス)", "単方向通信", "マルチプレックス通信"],
    correctIndex: 0,
    explanation: "全二重通信では送信と受信を分離した回線で同時に行うためデータ衝突（コリジョン）が発生しません。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-011",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "光ファイバーケーブルの規格で、コア径が非常に小さく光の乱反射を抑えて長距離伝送に適したタイプの名称はどれか？",
    options: ["シングルモードファイバー (SMF)", "マルチモードファイバー (MMF)", "同軸ケーブル", "シールドツイストペア (STP)"],
    correctIndex: 0,
    explanation: "シングルモードファイバーはレーザー光を用いて長距離でも減衰や遅延が少なく高速伝送が可能です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-012",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "リピータハブ等の半二重通信でパケットの衝突（コリジョン）が及ぶ物理接続の範囲を何と呼ぶか？",
    options: ["コリジョンドメイン", "ブロードキャストドメイン", "ルーティングドメイン", "サブネットドメイン"],
    correctIndex: 0,
    explanation: "レイヤ2スイッチはポートごとにコリジョンドメインを分割できるため衝突リスクをなくします。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-013",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "ARPリクエスト等のブロードキャストフレーム（宛先が全端末）が伝搬して到達する範囲を何と呼ぶか？",
    options: ["ブロードキャストドメイン", "コリジョンドメイン", "マルチキャストグループ", "ホップドメイン"],
    correctIndex: 0,
    explanation: "ブロードキャストドメインはルーター（またはVLAN分割）によってのみ分割されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-014",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "イーサネットフレームの宛先MACアドレスすべてに「1 (FF:FF:FF:FF:FF:FF)」がセットされた通信種別はどれか？",
    options: ["ブロードキャスト", "ユニキャスト", "マルチキャスト", "エニーキャスト"],
    correctIndex: 0,
    explanation: "FF:FF:FF:FF:FF:FF は同一ネットワーク上のすべての端末にメッセージを送るブロードキャストアドレスです。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-015",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "特定の「1対1」で通信を行う最も標準的なパケット転送方式はどれか？",
    options: ["ユニキャスト", "ブロードキャスト", "マルチキャスト", "エニーキャスト"],
    correctIndex: 0,
    explanation: "特定の1台の宛先IPまたは宛先MACのみを指定する1対1通信をユニキャストと呼びます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-016",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "特定のグループ（複数の端末）に対して同時に同一データパケットを効率よく配信する通信方式はどれか？",
    options: ["マルチキャスト", "ブロードキャスト", "ユニキャスト", "ポイントトゥポイント"],
    correctIndex: 0,
    explanation: "動画配信やルーティングプロトコルの情報交換など、特定の複数グループメンバー宛にはマルチキャストが使われます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-017",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "PoE (Power over Ethernet) とはどのような技術・機能か？",
    options: [
      "通常のイーサネットLANケーブルを通じて、データ通信と同時に電力も供給する技術",
      "通信ケーブルの断線を自動で補修する技術",
      "光ファイバーの通信速度を2倍にする技術",
      "無線アクセスポイント間の干渉を除去する技術",
    ],
    correctIndex: 0,
    explanation: "PoEにより、IP電話や無線アクセスポイント等へ電源コンセント不要で配線供給が可能になります。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-018",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "データ送信において、各レイヤ（層）が自身の制御ヘッダを元データに付加していく処理過程を何と呼ぶか？",
    options: ["カプセル化 (Encapsulation)", "デカプセル化 (Decapsulation)", "セグメンテーション", "フラグメンテーション"],
    correctIndex: 0,
    explanation: "送信側で上位層から下位層へとヘッダを包み込む処理をカプセル化、受信側で剥がす処理をデカプセル化と呼びます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-019",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "イーサネットインターフェース間で通信速度や全二重/半二重モードを自動的に調整して一致させる機能はどれか？",
    options: ["オートネゴシエーション", "オートMDI/MDI-X", "CSMA/CD", "STP"],
    correctIndex: 0,
    explanation: "オートネゴシエーションにより双方の最高性能（例: 1000Mbps/Full Duplex）が自動選択されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-020",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "スイッチのポートにおいて、接続されたLANケーブルがストレートかクロスかを自動判別して送受信ピンを自動切替する機能はどれか？",
    options: ["オートMDI/MDI-X", "オートネゴシエーション", "ポートセキュリティ", "PoE"],
    correctIndex: 0,
    explanation: "オートMDI/MDI-X機能により、クロスケーブルを用意しなくてもストレートケーブルで機器間通信が可能になります。",
    difficulty: "beginner",
  },

  // ─── CCNA: IPアドレッシング (15問) ──────────────────────────────────────────
  {
    questionId: "q-ccna-021",
    cert: "ccna",
    category: "IPアドレッシング",
    text: "IPv4アドレスのビット長として正しいものはどれか？",
    options: ["32ビット (4バイト)", "48ビット (6バイト)", "64ビット (8バイト)", "128ビット (16バイト)"],
    correctIndex: 0,
    explanation: "IPv4は8ビットごとにドットで区切った32ビットのアドレス構成です（例: 192.168.1.1）。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-022",
    cert: "ccna",
    category: "IPアドレッシング",
    text: "クラスCの標準的なプライベートIPv4アドレスの範囲として正しいものはどれか？",
    options: [
      "192.168.0.0 〜 192.168.255.255",
      "10.0.0.0 〜 10.255.255.255",
      "172.16.0.0 〜 172.31.255.255",
      "169.254.0.0 〜 169.254.255.255",
    ],
    correctIndex: 0,
    explanation: "192.168.0.0/16 がクラスCのプライベート範囲です。10.0.0.0/8はクラスA、172.16.0.0/12はクラスBです。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-023",
    cert: "ccna",
    category: "IPアドレッシング",
    text: "プレフィックス長「/24」を表すサブネットマスクの10進数表記として正しいものはどれか？",
    options: ["255.255.255.0", "255.255.0.0", "255.255.255.128", "255.255.255.255"],
    correctIndex: 0,
    explanation: "先頭から24ビット連続して「1」が立つ仕様のため、10進数では 255.255.255.0 になります。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-024",
    cert: "ccna",
    category: "IPアドレッシング",
    text: "プレフィックス長「/24」のネットワーク (例: 192.168.1.0/24) において、実際にPCや機器に割り当て可能な有効ホスト数はいくつか？",
    options: ["254台", "256台", "255台", "128台"],
    correctIndex: 0,
    explanation: "全256個のアドレス中、ネットワークアドレス(最初)とブロードキャストアドレス(最後)の2個を除いた 254個 が割り当て可能です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-025",
    cert: "ccna",
    category: "IPアドレッシング",
    text: "IPv4において、自分自身を指し示すために使用されるループバックアドレスとして標準的なものはどれか？",
    options: ["127.0.0.1", "0.0.0.0", "255.255.255.255", "169.254.0.1"],
    correctIndex: 0,
    explanation: "127.0.0.1 (localhost) は端末自身のTCP/IPプロトコルスタックが正常動作しているかの確認に用いられます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-026",
    cert: "ccna",
    category: "IPアドレッシング",
    text: "DHCPサーバーからIPを取得できなかった際に、端末が自動的に設定するリンクローカルアドレス (APIPA) の範囲はどれか？",
    options: ["169.254.0.0/16", "192.168.0.0/16", "10.0.0.0/8", "172.16.0.0/12"],
    correctIndex: 0,
    explanation: "169.254.x.x のアドレスはAPIPA機能により同一セグメント内の一時通信目的で自動設定されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-027",
    cert: "ccna",
    category: "IPアドレッシング",
    text: "IPv6アドレスのビット長として正しいものはどれか？",
    options: ["128ビット (16バイト)", "32ビット (4バイト)", "64ビット (8バイト)", "256ビット (32バイト)"],
    correctIndex: 0,
    explanation: "IPv6は128ビットのアドレス空間を持ち、約3.4×10^38個という事実上無限のアドレスを提供します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-028",
    cert: "ccna",
    category: "IPアドレッシング",
    text: "IPv6において、自分自身のループバックアドレス（localhost）を表す省略記法はどれか？",
    options: ["::1", "::0", "FE80::1", "FF00::1"],
    correctIndex: 0,
    explanation: "IPv6のループバックは 0:0:0:0:0:0:0:1 を省略形にした ::1 です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-029",
    cert: "ccna",
    category: "IPアドレッシング",
    text: "IPv6アドレスの中で、同一リンク（同一サブネット）内のみで自動生成して利用されるリンクローカルアドレスのプレフィックスはどれか？",
    options: ["FE80::/10", "2001::/16", "FF00::/8", "FC00::/7"],
    correctIndex: 0,
    explanation: "FE80::/10 から始まるアドレスは、ルーターや近隣ノードとの通信に各インターフェースが必須で持ちます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-030",
    cert: "ccna",
    category: "IPアドレッシング",
    text: "インターネット上で一意であり、グローバルにルーティング可能なIPv6アドレス（グローバルユニキャストアドレス）の一般的な先頭プレフィックスはどれか？",
    options: ["2000::/3", "FE80::/10", "FF00::/8", "FD00::/8"],
    correctIndex: 0,
    explanation: "現在インターネットで配布されているIPv6アドレスの大半は 2 または 3 で始まる 2000::/3 の範囲です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-031",
    cert: "ccna",
    category: "IPアドレッシング",
    text: "宛先IPアドレスに対応する通信相手のMACアドレスを問い合わせるためのプロトコルはどれか？",
    options: ["ARP (Address Resolution Protocol)", "DNS", "DHCP", "ICMP"],
    correctIndex: 0,
    explanation: "ARPはIPアドレスから物理的なMACアドレスを解決するためにブロードキャストで問い合わせます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-032",
    cert: "ccna",
    category: "IPアドレッシング",
    text: "PCやスマートフォン等に対し、IPアドレスやデフォルトゲートウェイ、DNSサーバー情報を自動的に割り当てるプロトコルはどれか？",
    options: ["DHCP", "DNS", "ARP", "NTP"],
    correctIndex: 0,
    explanation: "DHCPサーバーがネットワーク設定情報を自動配布することで端末ごとの手動設定を不要にします。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-033",
    cert: "ccna",
    category: "IPアドレッシング",
    text: "人間の覚えやすいドメイン名（例: www.cisco.com）とIPアドレスの変換（名前解決）を行うシステムはどれか？",
    options: ["DNS (Domain Name System)", "DHCP", "NAT", "HTTP"],
    correctIndex: 0,
    explanation: "DNSはインターネット上の電話帳としてドメイン名とIPの対応を解決します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-034",
    cert: "ccna",
    category: "IPアドレッシング",
    text: "社内のプライベートIPアドレスを、インターネット接続時にグローバルIPアドレスへ自動変換する機能はどれか？",
    options: ["NAT (または NAPT/PAT)", "ARP", "DHCP", "VPN"],
    correctIndex: 0,
    explanation: "NAT/PATにより、少数のグローバルIPアドレスで社内の多数の機器がインターネットにアクセスできます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-035",
    cert: "ccna",
    category: "IPアドレッシング",
    text: "ネットワーク診断ツール「ping」や「traceroute」が裏側で使用している、エラーメッセージや疎通確認用プロトコルはどれか？",
    options: ["ICMP (Internet Control Message Protocol)", "UDP", "TCP", "HTTP"],
    correctIndex: 0,
    explanation: "ICMPはネットワークの疎通状態や到達不能エラーなどを報告する必須の診断プロトコルです。",
    difficulty: "beginner",
  },

  // ─── CCNA: ルーティング (20問) ──────────────────────────────────────────────
  {
    questionId: "q-ccna-036",
    cert: "ccna",
    category: "ルーティング",
    text: "ルーターのルーティングテーブルに登録される「デフォルトルート」を表すネットワークアドレス表記はどれか？",
    options: ["0.0.0.0/0", "255.255.255.255/32", "127.0.0.1/8", "192.168.0.0/16"],
    correctIndex: 0,
    explanation: "0.0.0.0 0.0.0.0 はすべての宛先ネットワークにマッチするデフォルトルートとして機能します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-037",
    cert: "ccna",
    category: "ルーティング",
    text: "管理者がルーターに手動で宛先ネットワークと次ホップ先を固定設定するルーティング手法を何と呼ぶか？",
    options: ["スタティックルーティング", "ダイナミックルーティング", "デフォルトルーティング", "自動ルーティング"],
    correctIndex: 0,
    explanation: "スタティックルーティングはルーター間負荷がゼロですが、変更時は手動変更が必要です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-038",
    cert: "ccna",
    category: "ルーティング",
    text: "ルーター同士がルーティングプロトコルを用いて自動的に経路情報を交換し合う手法を何と呼ぶか？",
    options: ["ダイナミックルーティング", "スタティックルーティング", "手動ルーティング", "スタブルーティング"],
    correctIndex: 0,
    explanation: "OSPFやRIP等によりネットワーク障害時の自動経路切り替え（収束）が可能です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-039",
    cert: "ccna",
    category: "ルーティング",
    text: "異なるルーティング情報源（スタティックやOSPF等）が競合した際、ルーターがどれを優先するかを決める信頼度の指標値はどれか？",
    options: ["アドミニストレーティブディスタンス (AD値)", "メトリック", "ホップ数", "帯域幅コスト"],
    correctIndex: 0,
    explanation: "AD値が小さいほど信頼度が高くテーブルに採用されます（直接接続:0、スタティック:1、OSPF:110など）。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-040",
    cert: "ccna",
    category: "ルーティング",
    text: "同一ルーティングプロトコル内で、複数の到達経路がある場合に「最もコストが低い最適経路」を選択する判断基準となる値はどれか？",
    options: ["メトリック", "AD値", "ポート番号", "AS番号"],
    correctIndex: 0,
    explanation: "OSPFのコストやRIPのホップ数などがメトリックとして最適経路の評価に使用されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-041",
    cert: "ccna",
    category: "ルーティング",
    text: "企業内や同一組織などの単一の管理ドメイン内 (AS内) で動作するルーティングプロトコル群の総称はどれか？",
    options: ["IGP (Interior Gateway Protocol)", "EGP (Exterior Gateway Protocol)", "BGP", "WANプロトコル"],
    correctIndex: 0,
    explanation: "OSPF、RIP、EIGRPはすべて自律システム (AS) 内で用いられる IGP に分類されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-042",
    cert: "ccna",
    category: "ルーティング",
    text: "インターネット上のISP間など、異なる自律システム (AS) 同士を結ぶための現在事実上の唯一の外部ルーティングプロトコルはどれか？",
    options: ["BGP (Border Gateway Protocol)", "OSPF", "RIP", "EIGRP"],
    correctIndex: 0,
    explanation: "BGPはインターネット全体の経路制御を行うパスベクター型の EGP プロトコルです。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-043",
    cert: "ccna",
    category: "ルーティング",
    text: "リンクステート型アルゴリズム (SPF) を採用し、帯域幅から求めたコストをもとに最短経路を計算する代表的な IGP プロトコルはどれか？",
    options: ["OSPF", "RIP", "EIGRP", "BGP"],
    correctIndex: 0,
    explanation: "OSPF はマルチベンダーで広く普及しているリンクステート型の高速プロトコルです。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-044",
    cert: "ccna",
    category: "ルーティング",
    text: "Cisco ルーターにおいて、スタティックルートを定義するための設定コマンドとして正しいものはどれか？",
    options: [
      "ip route <宛先NW> <サブネットマスク> <ネクストホップIP>",
      "router static <宛先NW> <ネクストホップIP>",
      "set route <宛先NW> <ネクストホップIP>",
      "add ip-route <宛先NW>",
    ],
    correctIndex: 0,
    explanation: "例: ip route 0.0.0.0 0.0.0.0 192.168.1.254 でデフォルトルートを設定します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-045",
    cert: "ccna",
    category: "ルーティング",
    text: "Cisco ルーターにおいて、現在記録・採用されているルーティングテーブル一覧を表示するコマンドはどれか？",
    options: ["show ip route", "show ip interface brief", "show running-config", "show routing-table"],
    correctIndex: 0,
    explanation: "show ip route で各宛先へのルーティング情報、AD値、メトリックを確認できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-046",
    cert: "ccna",
    category: "ルーティング",
    text: "OSPF ルーティングのルーターID (Router ID) として自動選択される最優先ルールとして正しいものはどれか？",
    options: [
      "手動設定した router-id コマンド > 最大のループバックIP > 最大の物理インターフェースIP",
      "最小の物理インターフェースIP",
      "ルーターのMACアドレス",
      "ホスト名を数字変換した値",
    ],
    correctIndex: 0,
    explanation: "明示的に router-id コマンドを設定するのが運用の基本ルールです。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-047",
    cert: "ccna",
    category: "ルーティング",
    text: "OSPF の設定で、インターフェースから OSPF ルーティング更新情報の送信を停止しつつ、そのインターフェースのネットワークを広告する設定コマンドはどれか？",
    options: ["passive-interface <インターフェース名>", "no ospf transmit", "silent-interface", "block-ospf"],
    correctIndex: 0,
    explanation: "PCが接続するLAN側インターフェース等には passive-interface を設定して安全性を高めます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-048",
    cert: "ccna",
    category: "ルーティング",
    text: "OSPF エリア0 (Area 0) が持つ特別な役割の名称はどれか？",
    options: ["バックボーンエリア (Backbone Area)", "スタブエリア", "トータリースタブエリア", "通常エリア"],
    correctIndex: 0,
    explanation: "すべての非バックボーンエリアは、エリア0 を中心に接続して通信情報をやり取りする必要があります。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-049",
    cert: "ccna",
    category: "ルーティング",
    text: "ルーティングテーブルを簡素化しメモリを節約するため、複数の細かいサブネットを1つの大きなネットワークアドレスに統合することを何と呼ぶか？",
    options: ["経路集約 (ルートサマライゼーション)", "フラグメンテーション", "サブネッティング", "カプセル化"],
    correctIndex: 0,
    explanation: "経路集約を行うことでルーターの負荷を削減し、ルーティングの安定性を大きく向上させます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-050",
    cert: "ccna",
    category: "ルーティング",
    text: "ルーター間での動的なルーティング情報が全体に行き渡り、全機器で正確な経路テーブルが一致・安定した状態を何と呼ぶか？",
    options: ["コンバージェンス (収束)", "フラッディング", "アジャセンシー", "シンクロナイゼーション"],
    correctIndex: 0,
    explanation: "コンバージェンスにかかる時間が短いルーティングプロトコルほど、障害対応能力に優れます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-051",
    cert: "ccna",
    category: "ルーティング",
    text: "ディスタンスベクタ型プロトコル (RIP等) の主なルーティング評価指標として用いられる、宛先までのルーター通過回数を表す言葉はどれか？",
    options: ["ホップ数 (Hop Count)", "コスト (Cost)", "帯域幅 (Bandwidth)", "遅延 (Delay)"],
    correctIndex: 0,
    explanation: "RIPでは経由するルーターの数（ホップ数）が最も少ない経路を最適経路と判断します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-052",
    cert: "ccna",
    category: "ルーティング",
    text: "Cisco ルーターのコンソール上で、すべてのインターフェースのIPアドレス設定および起動ステータス（Up/Down）を要約して表示するコマンドはどれか？",
    options: ["show ip interface brief", "show running-config", "show interfaces", "show ip route"],
    correctIndex: 0,
    explanation: "略して sh ip int br と入力し、各ポートの接続状態を確認するのに最も便利なコマンドです。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-053",
    cert: "ccna",
    category: "ルーティング",
    text: "Cisco ルーターのインターフェースはデフォルトでどのような管理状態になっているか？",
    options: ["シャットダウン状態 (shutdown・無効)", "アクティブ状態 (no shutdown・有効)", "パッシブ状態", "自動学習状態"],
    correctIndex: 0,
    explanation: "ルーターの各ポートは安全のため初期状態で無効化されているため、設定時は必ず no shutdown が必要です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-054",
    cert: "ccna",
    category: "ルーティング",
    text: "ルーティングテーブルにおいて、直接ルーターのインターフェースに接続されているネットワーク（直接接続ルート）のAD値 (アドミニストレーティブディスタンス) はどれか？",
    options: ["0", "1", "110", "120"],
    correctIndex: 0,
    explanation: "直接接続は AD=0、スタティックルートは AD=1、OSPFは AD=110 と定義されています。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-055",
    cert: "ccna",
    category: "ルーティング",
    text: "ルーターのシリアルインターフェースやギガビットインターフェースにおいて、説明コメントや用途のメモを追加するためのコマンドはどれか？",
    options: ["description <コメント文>", "comment <コメント文>", "note <コメント文>", "remark <コメント文>"],
    correctIndex: 0,
    explanation: "インターフェース設定モードで description コマンドを記載し、配線先の名称等を分かりやすく管理します。",
    difficulty: "beginner",
  },

  // ─── CCNA: スイッチング・VLAN (15問) ─────────────────────────────────────────
  {
    questionId: "q-ccna-056",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "レイヤ2スイッチがフレームを受信した際、送信元MACアドレスを記録して構築する学習テーブルの名称はどれか？",
    options: ["MACアドレステーブル", "ルーティングテーブル", "ARPテーブル", "VLANデータベース"],
    correctIndex: 0,
    explanation: "スイッチはフレームの送信元MACを見て MACアドレステーブル（CAMテーブル）を自動作成します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-057",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "レイヤ2スイッチに宛先MACアドレスがテーブルに登録されていないフレーム（未知のユニキャスト）が届いた場合、スイッチはどのような動作を行うか？",
    options: ["受信ポートを除く全ポートにフレームを転送（フラッディング）する", "フレームを破棄する", "ルーターへ転送する", "送信元へエラーを返す"],
    correctIndex: 0,
    explanation: "テーブル未登録の宛先にはフラッディングを行い、通信相手からの応答によってMACアドレスを新たに学習します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-058",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "物理的な接続ポートに関わらず、スイッチ内部でネットワークを論理的に分割してセキュリティと効率を高める技術はどれか？",
    options: ["VLAN (Virtual LAN)", "STP", "PoE", "VRF"],
    correctIndex: 0,
    explanation: "VLANによりブロードキャストドメインを分割できるため、部署ごと等の安全で効率的な構成が可能です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-059",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "特定の単一VLANにのみ所属し、主にPCやプリンタなどの端末を接続するスイッチポートのモード名として正しいものはどれか？",
    options: ["アクセスポート (Access Port)", "トランクポート (Trunk Port)", "ダイナミックポート", "モニターポート"],
    correctIndex: 0,
    explanation: "アクセスポートは送受信フレームにVLANタグを付加せず、指定された単一VLANとして扱います。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-060",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "スイッチ間やルーターとの間を結ぶケーブルで、1本のリンク上に複数の異なるVLANフレームをまとめて伝送できるポートモードはどれか？",
    options: ["トランクポート (Trunk Port)", "アクセスポート (Access Port)", "プライベートVLANポート", "ルーテッドポート"],
    correctIndex: 0,
    explanation: "トランクポートに設定することで、多数のVLANデータをそれぞれのタグで区別しながら通信可能です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-061",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "イーサネットフレームのヘッダに4バイトのタグを挿入し、VLAN識別番号(VLAN ID)を付与する業界標準のトランキングプロトコル規格はどれか？",
    options: ["IEEE 802.1Q", "IEEE 802.1X", "IEEE 802.3ad", "ISL"],
    correctIndex: 0,
    explanation: "IEEE 802.1Q は全メーカーの機器間で互換性のある標準的なVLANタギング規格です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-062",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "トランクリンク上で、あえてVLANタグを付与しない（アンタグド）状態で伝送される特別な標準VLAN (デフォルトはVLAN 1) を何と呼ぶか？",
    options: ["ネイティブVLAN (Native VLAN)", "マネジメントVLAN", "ボイスVLAN", "デフォルトVLAN"],
    correctIndex: 0,
    explanation: "ネイティブVLANはトランクリンクにおいてタグなしで通信され、両端のスイッチで一致設定が必要です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-063",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "Cisco スイッチにおいて、新しい VLAN 10 を作成し、名前を「Sales」に設定する一連のコマンドとして正しいものはどれか？",
    options: [
      "vlan 10 -> name Sales",
      "create vlan 10 Sales",
      "interface vlan 10 -> title Sales",
      "vlan-add 10 name Sales",
    ],
    correctIndex: 0,
    explanation: "グローバルコンフィグで vlan 10 を実行し、そのサブモードで name <名称> を設定します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-064",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "スイッチインターフェース GigabitEthernet 0/1 を、アクセスポートにして VLAN 10 に割り当てるコマンドはどれか？",
    options: [
      "switchport mode access -> switchport access vlan 10",
      "switchport trunk vlan 10",
      "vlan 10 port g0/1",
      "assign vlan 10 access",
    ],
    correctIndex: 0,
    explanation: "まず switchport mode access を指定し、続けて switchport access vlan <ID> を設定します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-065",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "Cisco スイッチにおいて、設定されているVLAN ID、名称、および割り振られたポート一覧を要約して確認するコマンドはどれか？",
    options: ["show vlan brief", "show switchport", "show vlan all", "show interfaces vlan"],
    correctIndex: 0,
    explanation: "sh vlan br で、VLAN設定と各ポートの所属状況を最もシンプルにチェックできます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-066",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "スイッチネットワークで冗長構成を組んだ際に発生するフレームの永久ループを防止し、自動で迂回路を制御するプロトコルはどれか？",
    options: ["STP (Spanning Tree Protocol)", "ARP", "LACP", "LLDP"],
    correctIndex: 0,
    explanation: "IEEE 802.1D STP はループを自動検知してポートの一部を論理的にブロックします。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-067",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "STP (スパニングツリー) において、各スイッチが情報交換のために定期的に送受信する制御用メッセージフレームの名称はどれか？",
    options: ["BPDU (Bridge Protocol Data Unit)", "ARP Packet", "Hello Frame", "LLDP PDU"],
    correctIndex: 0,
    explanation: "スイッチ間はBPDUを交換してツリー構造の計算やルートブリッジの選出を行います。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-068",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "STPの収束を高速化するため、PC等が接続されるアクセスポートをリスニング／ラーニング状態をスキップして即時に転送可能にする設定はどれか？",
    options: ["PortFast", "BPDU Guard", "UplinkFast", "Root Guard"],
    correctIndex: 0,
    explanation: "PortFast を設定したアクセスポートはリンクアップ後ただちにフォワーディング状態へ遷移します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-069",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "複数の物理的なイーサネット回線を論理的に1本の太い回線に束ねて、帯域幅増強と冗長性を高める技術（リンクアグリゲーション）の規格はどれか？",
    options: ["LACP (IEEE 802.3ad)", "STP", "VLAN", "PoE"],
    correctIndex: 0,
    explanation: "LACP または EtherChannel により、物理ポート障害時の無瞬断継続と帯域拡張を実現します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-070",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "異なる VLAN 間（例: VLAN 10 の PC と VLAN 20 の PC）でパケットを転送・やり取りするために必ず必要となる機器または機能はどれか？",
    options: ["ルーター または レイヤ3スイッチ", "レイヤ2スイッチ", "リピータハブ", "モデム"],
    correctIndex: 0,
    explanation: "VLAN間はブロードキャストが届かないため、レイヤ3でのルーティング処理が不可欠です。",
    difficulty: "beginner",
  },

  // ─── CCNA: セキュリティ (15問) ───────────────────────────────────────────────
  {
    questionId: "q-ccna-071",
    cert: "ccna",
    category: "セキュリティ",
    text: "ルーターやスイッチにおいて、IPアドレスやポート番号などの条件に基づきトラフィックの許可・拒否を行うフィルタリング機能はどれか？",
    options: ["ACL (アクセス制御リスト / Access Control List)", "NAT", "STP", "QoS"],
    correctIndex: 0,
    explanation: "ACLを用いることで通信制御や不要トラフィック・攻撃パケットの排除が可能です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-072",
    cert: "ccna",
    category: "セキュリティ",
    text: "Cisco ルーターの「標準 ACL (Standard ACL)」が検査対象とするパケット内の情報はどれか？",
    options: ["送信元 IP アドレスのみ", "送信元と宛先の IP アドレス両方", "TCP/UDP ポート番号", "宛先 MAC アドレス"],
    correctIndex: 0,
    explanation: "番号 1〜99 等を使う標準ACLは送信元IPのみを評価するため、通常は宛先に近いルーターに適用します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-073",
    cert: "ccna",
    category: "セキュリティ",
    text: "「拡張 ACL (Extended ACL)」で制御条件として指定可能な条件の組み合わせとして正しいものはどれか？",
    options: [
      "送信元・宛先のIPアドレス、プロトコル種別、TCP/UDPポート番号",
      "送信元IPアドレスのみ",
      "ホスト名とMACアドレス",
      "VLAN IDとVLAN名",
    ],
    correctIndex: 0,
    explanation: "番号 100〜199 等を使う拡張ACLは非常に細かく制御でき、通常は送信元の近いルーターに適用します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-074",
    cert: "ccna",
    category: "セキュリティ",
    text: "Cisco の ACL に標準で設定されており、明示的に permit（許可）しなかった通信が最終行ですべて自動的に拒否される動作を何と呼ぶか？",
    options: ["暗黙の Deny (Implicit Deny)", "デフォルト Permit", "フォールバックシャットダウン", "ゼロトラスト"],
    correctIndex: 0,
    explanation: "ACLの末尾には見えない形で「deny any」が存在するため、許可ルールが一つは必要です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-075",
    cert: "ccna",
    category: "セキュリティ",
    text: "スイッチのポートにおいて、接続する端末のMACアドレス数を制限し、不正な持ち込みPCの接続を防ぐセキュリティ機能はどれか？",
    options: ["ポートセキュリティ (Port Security)", "DHCPスヌーピング", "ダイナミックARPインスペクション", "BPDUガード"],
    correctIndex: 0,
    explanation: "ポートセキュリティにより違反時にポートをシャットダウンまたは破棄制限できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-076",
    cert: "ccna",
    category: "セキュリティ",
    text: "無線LAN（Wi-Fi）における最新の標準セキュリティ規格で、SAE認証を用いて辞書攻撃耐性を高めた規格はどれか？",
    options: ["WPA3", "WPA2", "WEP", "WPA-PSK"],
    correctIndex: 0,
    explanation: "WPA3 は最新のWi-Fi推奨暗号規格で、個々の接続ごとに強力な認証暗号化を提供します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-077",
    cert: "ccna",
    category: "セキュリティ",
    text: "ネットワーク管理機器へのリモートアクセスにおいて、通信経路上のパスワードやデータを暗号化する安全なプロトコルはどれか？",
    options: ["SSH (Secure Shell)", "Telnet", "HTTP", "FTP"],
    correctIndex: 0,
    explanation: "従来の Telnet (ポート23) は平文で盗聴される危険があるため、暗号化された SSH (ポート22) を使います。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-078",
    cert: "ccna",
    category: "セキュリティ",
    text: "偽のDHCPサーバーを社内に設置されたことによるIP情報やDNSの改ざん（中間者攻撃）をスイッチ側で防ぐ機能はどれか？",
    options: ["DHCPスヌーピング (DHCP Snooping)", "ポートセキュリティ", "プライベートVLAN", "STP BPDUガード"],
    correctIndex: 0,
    explanation: "正規のDHCPサーバー接続ポートのみを信頼(Trusted)に設定し、偽の応答パケットを自動遮断します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-079",
    cert: "ccna",
    category: "セキュリティ",
    text: "LAN内でのなりすまし（ARPスプーフィング攻撃）を防ぐため、DHCPスヌーピングの情報を基に不正なARPパケットをブロックする機能はどれか？",
    options: ["DAI (Dynamic ARP Inspection)", "IP Source Guard", "802.1X", "RADIUS"],
    correctIndex: 0,
    explanation: "DAI機能によりIPアドレスとMACアドレスの不一致がある偽造ARP応答を廃棄します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-080",
    cert: "ccna",
    category: "セキュリティ",
    text: "社内ネットワークのスイッチポートにPCを接続した際、認証サーバーと連携してユーザー認証が完了するまで通信を許可しない認証規格はどれか？",
    options: ["IEEE 802.1X 認証", "WPA3", "ポートセキュリティ", "MACフィルタリング"],
    correctIndex: 0,
    explanation: "IEEE 802.1X はサプリカント(端末)、オーセンティケーター(スイッチ)、RADIUSサーバーの3者で強力認証を行います。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-081",
    cert: "ccna",
    category: "セキュリティ",
    text: "Cisco 機器の特権EXECモード（enable）へ移行するパスワードを強力なハッシュ関数で暗号化設定する推奨コマンドはどれか？",
    options: ["enable secret <パスワード>", "enable password <パスワード>", "service password-encryption", "username admin secret"],
    correctIndex: 0,
    explanation: "enable secret で設定されたパスワードはMD5やSHA-256で安全に保存されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-082",
    cert: "ccna",
    category: "セキュリティ",
    text: "外部からの攻撃や不正侵入パケットをネットワークの境界で監視し、リアルタイムに検知して通知するシステムを何と呼ぶか？",
    options: ["IDS (侵入検知システム)", "IPS (侵入防御システム)", "ファイアウォール", "プロキシ"],
    correctIndex: 0,
    explanation: "IDS (Intrusion Detection System) は検知・通報を行い、IPS (Prevention) はさらに遮断処理まで行います。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-083",
    cert: "ccna",
    category: "セキュリティ",
    text: "使用されていないスイッチの物理ポートに対する最も確実な基本セキュリティ対策として推奨される設定はどれか？",
    options: ["ポートを shutdown (無効化) して、未使用VLANに移動する", "すべてトランクポートに設定する", "STPを無効にする", "PoEを最大出力にする"],
    correctIndex: 0,
    explanation: "空きポートを shutdown にしておくことで、無断でのLANケーブル接続による侵入を完全に防ぎます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-084",
    cert: "ccna",
    category: "セキュリティ",
    text: "公衆回線やインターネット上に、暗号化技術を用いて仮想的な専用プライベートトンネルを構築して安全通信を行う技術はどれか？",
    options: ["VPN (Virtual Private Network)", "VLAN", "NAT", "SDN"],
    correctIndex: 0,
    explanation: "IPsec VPN や SSL/TLS VPN を用いることで、リモートワークでも安全に社内LANへ接続できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-085",
    cert: "ccna",
    category: "セキュリティ",
    text: "パスワードなどの認証情報を機器内部に直接持たせず、中央の認証サーバー (AAA) で一元管理するために使用されるプロトコルはどれか？",
    options: ["RADIUS (または TACACS+)", "SSH", "SNMP", "NTP"],
    correctIndex: 0,
    explanation: "AAA (Authentication, Authorization, Accounting) サーバーとして RADIUS や TACACS+ が利用されます。",
    difficulty: "beginner",
  },

  // ─── CCNA: WAN・クラウド・自動化 (15問) ──────────────────────────────────────
  {
    questionId: "q-ccna-086",
    cert: "ccna",
    category: "WAN・クラウド・自動化",
    text: "ソフトウェアによってネットワークの制御(コントロールプレーン)をデータ転送(データプレーン)から分離し、集中管理する技術はどれか？",
    options: ["SDN (Software-Defined Networking)", "STP", "VLAN", "SNMP"],
    correctIndex: 0,
    explanation: "SDNによりコントローラーが全体を一元管理・設定適用し、自動化や運用の柔軟性を高めます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-087",
    cert: "ccna",
    category: "WAN・クラウド・自動化",
    text: "クラウドサービスの提供形態で、AWS EC2や仮想マシン、ストレージなどの「インフラ基盤そのもの」を提供するサービスモデルはどれか？",
    options: ["IaaS (Infrastructure as a Service)", "PaaS (Platform as a Service)", "SaaS (Software as a Service)", "FaaS"],
    correctIndex: 0,
    explanation: "IaaS はサーバー環境のハードウェア・ネットワーク基盤を仮想的に提供する形態です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-088",
    cert: "ccna",
    category: "WAN・クラウド・自動化",
    text: "Webアプリケーション等で異なるサービス間がデータ連携を行う際、HTTPプロトコル（GETやPOST等）を用いて操作する標準的なAPIはどれか？",
    options: ["REST API (RESTful API)", "SOAP API", "XML-RPC", "CLI API"],
    correctIndex: 0,
    explanation: "REST APIはシンプルで扱いやすく、ネットワーク自動化でも最も標準的なインターフェースです。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-089",
    cert: "ccna",
    category: "WAN・クラウド・自動化",
    text: "REST API や Web サービス等でのデータ交換書式として現在最も広く用いられる、軽量で人間にも読みやすい構造化データ形式はどれか？",
    options: ["JSON (JavaScript Object Notation)", "XML", "HTML", "YAML"],
    correctIndex: 0,
    explanation: "JSON はキーと値のペアでシンプルに表現され、Cisco DNA Center API 等のレスポンス形式としても標準です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-090",
    cert: "ccna",
    category: "WAN・クラウド・自動化",
    text: "インフラ構成をコードで管理し、エージェント不要でSSHを通じてYAMLファイル (Playbook) の設定を多数機器に自動展開する構成管理ツールはどれか？",
    options: ["Ansible", "Puppet", "Chef", "Wireshark"],
    correctIndex: 0,
    explanation: "Ansible はオープンソースの定番自動化ツールで、ネットワーク機器のコンフィグ更新でも大いに役立ちます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-091",
    cert: "ccna",
    category: "WAN・クラウド・自動化",
    text: "REST API でリソースの「情報の取得 (読み出し)」をリクエストする際に主に使用する標準的な HTTP メソッドはどれか？",
    options: ["GET", "POST", "PUT", "DELETE"],
    correctIndex: 0,
    explanation: "GET=取得、POST=新規作成、PUT=変更・更新、DELETE=削除 の4大メソッドが基本になります。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-092",
    cert: "ccna",
    category: "WAN・クラウド・自動化",
    text: "HTTP レスポンスステータスコードにおいて、「404 Not Found」等が属する分類（400番台）の意味はどれか？",
    options: ["クライアントエラー (リクエストの誤り等)", "成功 (200番台)", "サーバーエラー (500番台)", "リダイレクト (300番台)"],
    correctIndex: 0,
    explanation: "400番台はクライアント側の指定ミスや権限不足等を示し、500番台がサーバー側障害を示します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-093",
    cert: "ccna",
    category: "WAN・クラウド・自動化",
    text: "SDN において、SDN コントローラーから下位の物理機器（ルーターやスイッチ等）を制御するためのインターフェースはどれか？",
    options: ["サウスバウンド API (Southbound API)", "ノースバウンド API", "イーストバウンド API", "ウエストバウンド API"],
    correctIndex: 0,
    explanation: "南側(下部)の機器接続用をサウスバウンド、北側(上部)の管理ソフト連携用をノースバウンドAPIと呼びます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-094",
    cert: "ccna",
    category: "WAN・クラウド・自動化",
    text: "ネットワーク仮想化技術の一つで、物理LANの上に仮想的なトンネルを張ることでVLAN IDの4094個の上限を超えた約1600万個の仮想LANを作る技術はどれか？",
    options: ["VXLAN (Virtual Extensible LAN)", "STP", "IEEE 802.1Q", "LACP"],
    correctIndex: 0,
    explanation: "VXLAN は大規模データセンターやクラウド環境で仮想マシン用LANを柔軟にスケールさせるコア技術です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-095",
    cert: "ccna",
    category: "WAN・クラウド・自動化",
    text: "Cisco が提供するエンタープライズ SDN ネットワークの統合管理基盤（コントローラー製品）の名称はどれか？",
    options: ["Cisco DNA Center (Catalyst Center)", "Cisco Packet Tracer", "Cisco IOS CLI", "Cisco AnyConnect"],
    correctIndex: 0,
    explanation: "Cisco DNA Center により、GUIやAPIを通じた構成管理、自動設定適用、アシュアランス(状態監視)が可能になります。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-096",
    cert: "ccna",
    category: "WAN・クラウド・自動化",
    text: "データセンターの構造で、サーバーと直接接続する「リーフスイッチ」と、それらを相互接続する「スパインスイッチ」の2層で構成されるアーキテクチャを何と呼ぶか？",
    options: ["スパイン・リーフ構造 (Spine-Leaf Architecture)", "3層階層モデル", "スタブトポロジー", "リングトポロジー"],
    correctIndex: 0,
    explanation: "サーバー間のトラフィック(East-Westトラフィック)を均一な遅延と高い帯域幅で高速処理する設計です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-097",
    cert: "ccna",
    category: "WAN・クラウド・自動化",
    text: "構成ファイルとして Ansible の Playbook などでも採用されている、インデントで階層を表現する非常に見やすいデータ定義言語はどれか？",
    options: ["YAML", "JSON", "XML", "CSV"],
    correctIndex: 0,
    explanation: "YAML (YAML Ain't Markup Language) はハイフンやスペースインデントで直感的にリストや構造を記述できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-098",
    cert: "ccna",
    category: "WAN・クラウド・自動化",
    text: "インフラ設定を一度適用した後、同じ自動化スクリプトを何回繰り返し実行しても常に同じ結果になり、意図しない設定変更が起きない性質を何と呼ぶか？",
    options: ["べき等性 (Idempotence)", "同期性", "スケーラビリティ", "アベイラビリティ"],
    correctIndex: 0,
    explanation: "Ansible 等の構成管理ツールは「べき等性」を保証するため安全に繰り返し実行できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-099",
    cert: "ccna",
    category: "WAN・クラウド・自動化",
    text: "ブロードバンドルーターや企業WAN等で、インターネット接続事業者(ISP)から認証を受けてPPPセッションをイーサネット上に確立するプロトコルはどれか？",
    options: ["PPPoE (PPP over Ethernet)", "IPsec", "VXLAN", "MPLS"],
    correctIndex: 0,
    explanation: "日本の光回線接続などでも広く利用されている回線認証およびカプセル化技術です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-100",
    cert: "ccna",
    category: "WAN・クラウド・自動化",
    text: "企業内ネットワークにおいて、通信機器からCPU使用率やインターフェースのトラフィック統計情報を中央モニターサーバーへ報告・監視させるプロトコルはどれか？",
    options: ["SNMP (Simple Network Management Protocol)", "NTP", "DHCP", "DNS"],
    correctIndex: 0,
    explanation: "SNMP により、MIB(管理情報ベース) を通じて機器の稼働状況や障害アラート(Trap)の集中管理が可能です。",
    difficulty: "beginner",
  },
];
