export interface SeedQuestion {
  questionId: string;
  cert: "lpic1" | "ccna";
  category: string;
  text: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  difficulty: "beginner" | "intermediate" | "advanced";
}

export const SEED_QUESTIONS: SeedQuestion[] = [
  // ─── LPIC-1: システムアーキテクチャ ─────────────────────────────────────
  {
    questionId: "q-lpic1-sysarch-01",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "BIOSとUEFIの違いについて正しい記述はどれか？",
    options: [
      "UEFIは2TB以上のディスクからの起動ができない",
      "UEFIはGPT（GUID Partition Table）をサポートしている",
      "BIOSはセキュアブートを標準サポートしている",
      "UEFIは16ビットモードでのみ動作する",
    ],
    correctIndex: 1,
    explanation:
      "UEFIはGPT（GUID Partition Table）をサポートし、2TBを超える大容量ディスクからの起動やセキュアブートが可能です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-sysarch-02",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "Linux起動時に接続されているPCIデバイスの一覧と詳細を表示するコマンドはどれか？",
    options: ["lsusb", "lspci", "lsdev", "pci-info"],
    correctIndex: 1,
    explanation:
      "lspci コマンドはPCIバスおよび接続されているデバイスの一覧を表示します。オプション -k で使用中のカーネルモジュールも確認可能です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-sysarch-03",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "systemd採用システムにおいて、現在のデフォルトターゲット（ランレベルに相当）を確認するコマンドはどれか？",
    options: [
      "systemctl get-default",
      "systemctl show-target",
      "systemctl list-default",
      "systemctl status target",
    ],
    correctIndex: 0,
    explanation:
      "systemctl get-default コマンドにより、現在のデフォルトのターゲットユニット（graphical.target や multi-user.target 等）を表示します。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-sysarch-04",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "カーネルモジュールとその依存関係を解決して自動でロードするコマンドはどれか？",
    options: ["insmod", "rmmod", "modinfo", "modprobe"],
    correctIndex: 3,
    explanation:
      "modprobe は modules.dep の依存関係情報を参照し、必要な依存モジュールを含めて自動でロードまたはアンロードします。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-sysarch-05",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "GRUB2の設定ファイル（/boot/grub/grub.cfg 等）を再生成する一般的なコマンドはどれか？（Debian系）",
    options: [
      "grub-mkconfig -o /boot/grub/grub.cfg",
      "grub-install /boot",
      "grub2-update",
      "make-grub-config",
    ],
    correctIndex: 0,
    explanation:
      "grub-mkconfig コマンド（Debian/Ubuntuでは update-grub）を使用して /boot/grub/grub.cfg を生成します。",
    difficulty: "advanced",
  },

  // ─── LPIC-1: パッケージ管理 ─────────────────────────────────────────
  {
    questionId: "q-lpic1-pkg-01",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "Debian/Ubuntu系システムで、パッケージリストのインデックスをサーバー側と同期して更新するコマンドはどれか？",
    options: ["apt update", "apt upgrade", "apt install", "dpkg --update"],
    correctIndex: 0,
    explanation:
      "apt update コマンドはリポジトリのパッケージ情報（インデックス）を最新状態へ更新します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-pkg-02",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "RPMパッケージがインストールしている全ファイルの一覧を表示する dpkg / rpm のオプションの組み合わせとして正しいものは？",
    options: [
      "rpm -ql パッケージ名",
      "rpm -qi パッケージ名",
      "rpm -qa",
      "rpm -e パッケージ名",
    ],
    correctIndex: 0,
    explanation:
      "rpm -ql (query list) コマンドにより、指定したパッケージに含まれる全ファイルパスを一覧表示します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-pkg-03",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "Red Hat/Fedora系システムにおいて、dnf/yumコマンドを使用して特定ファイルの提供元パッケージを検索する構文は？",
    options: [
      "dnf provides /path/to/file",
      "dnf search-file /path/to/file",
      "dnf list-file /path/to/file",
      "dnf find /path/to/file",
    ],
    correctIndex: 0,
    explanation:
      "dnf provides (または yum provides / whatprovides) により、指定したファイルやコマンドを提供するパッケージを特定できます。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-pkg-04",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "共有ライブラリキャッシュ（/etc/ld.so.cache）を再構築するためのコマンドはどれか？",
    options: ["ldconfig", "ldd", "ld.so.update", "libcache"],
    correctIndex: 0,
    explanation:
      "ldconfig コマンドを実行することで、/etc/ld.so.conf 等の設定に基づき共有ライブラリキャッシュを最新化します。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-pkg-05",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "Debian系システムで、ダウンロード済みの .deb パッケージをオフラインインストールする dpkg オプションはどれか？",
    options: [
      "dpkg -i file.deb",
      "dpkg -s file.deb",
      "dpkg -r file.deb",
      "dpkg -L file.deb",
    ],
    correctIndex: 0,
    explanation:
      "dpkg -i (または --install) を用いて .deb パッケージファイルを個別にインストールします。",
    difficulty: "beginner",
  },

  // ─── LPIC-1: 基本コマンド ─────────────────────────────────────────
  {
    questionId: "q-lpic1-cmd-01",
    cert: "lpic1",
    category: "基本コマンド",
    text: "ファイル内の特定の文字列を正規表現で検索する最も基本的なコマンドはどれか？",
    options: ["grep", "find", "sed", "awk"],
    correctIndex: 0,
    explanation:
      "grep コマンドはファイル内容からパターンに一致する行を抽出します。-v で一致しない行、-i で大文字小文字を無視します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-cmd-02",
    cert: "lpic1",
    category: "基本コマンド",
    text: "コマンドの標準出力を画面に表示しつつ、同時にファイルへ保存するコマンドはどれか？",
    options: ["tee", "cat", "echo", "pipe"],
    correctIndex: 0,
    explanation:
      "tee コマンドは標準入力を受け取り、標準出力と指定したファイルの両方へデータを複製して出力します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-cmd-03",
    cert: "lpic1",
    category: "基本コマンド",
    text: "find コマンドで更新日時が7日以上前の拡張子 .log のファイルを探して削除する正しい記述はどれか？",
    options: [
      "find /var/log -name '*.log' -mtime +7 -delete",
      "find /var/log -file '*.log' -date 7 -rm",
      "find /var/log --delete-days 7 '*.log'",
      "find /var/log -name '*.log' -days +7 -exec rm {}",
    ],
    correctIndex: 0,
    explanation:
      "-mtime +7 は7日より前に変更されたファイルを指し、-delete オプションまたは -exec rm {} \\; により削除が可能です。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-cmd-04",
    cert: "lpic1",
    category: "基本コマンド",
    text: "テキストファイルの指定した列を区切り文字で切り出して出力するコマンドはどれか？",
    options: ["cut", "paste", "split", "head"],
    correctIndex: 0,
    explanation:
      "cut コマンドは -d オプションで区切り文字を指定し、-f で取り出すフィールド（列番）を切り出して表示します。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-cmd-05",
    cert: "lpic1",
    category: "基本コマンド",
    text: "テキスト中の特定の文字列を置換してストリーム出力する代表的なコマンドツールはどれか？",
    options: ["sed", "wc", "tr", "join"],
    correctIndex: 0,
    explanation:
      "sed ('s/検索文字列/置換文字列/g') は非対話的にテキストの置換や行抽出・削除を行う強力なストリームエディタです。",
    difficulty: "advanced",
  },

  // ─── LPIC-1: ファイルシステム ─────────────────────────────────────
  {
    questionId: "q-lpic1-fs-01",
    cert: "lpic1",
    category: "ファイルシステム",
    text: "ファイルシステムのディスク使用量と空き容量を人が読みやすい単位（MB/GB等）で表示するコマンドはどれか？",
    options: ["df -h", "du -h", "fdisk -l", "lsblk"],
    correctIndex: 0,
    explanation:
      "df (disk free) -h (--human-readable) はマウントされている各ファイルシステムの空き容量を人が読みやすい単位で表示します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-fs-02",
    cert: "lpic1",
    category: "ファイルシステム",
    text: "GPT（GUID Partition Table）ディスクのパーティション操作に適した対話型ツールはどれか？",
    options: ["gdisk", "fdisk-mbr", "sfdisk-old", "mbrpart"],
    correctIndex: 0,
    explanation:
      "gdisk はGPTパーティションテーブル専用のコマンドライン対話ツールです（MBRディスクには fdisk を使用します）。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-fs-03",
    cert: "lpic1",
    category: "ファイルシステム",
    text: "システム起動時に自動マウントするデバイスとそのマウントポイントを定義する設定ファイルはどれか？",
    options: [
      "/etc/fstab",
      "/etc/mtab",
      "/etc/mount.conf",
      "/etc/filesystems",
    ],
    correctIndex: 0,
    explanation:
      "/etc/fstab（file system table）ファイルにデバイスUUID、マウントポイント、ファイルシステム種類、マウントオプションを記述します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-fs-04",
    cert: "lpic1",
    category: "ファイルシステム",
    text: "ext4 ファイルシステムを作成（フォーマット）する一般的なコマンドはどれか？",
    options: [
      "mkfs.ext4 /dev/sdb1",
      "format -t ext4 /dev/sdb1",
      "fsck.ext4 /dev/sdb1",
      "mount -t ext4 /dev/sdb1",
    ],
    correctIndex: 0,
    explanation:
      "mkfs.ext4 (または mkfs -t ext4) によりパーティション上に新しく ext4 ファイルシステムを構築します。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-fs-05",
    cert: "lpic1",
    category: "ファイルシステム",
    text: "シンボリックリンクとハードリンクの違いについて正しい説明はどれか？",
    options: [
      "ハードリンクは異なるファイルシステム間をまたいで作成できないが、シンボリックリンクは作成できる",
      "シンボリックリンクは元ファイルが削除されても参照先にデータが残る",
      "ハードリンクはディレクトリに対しても標準で自由に作成できる",
      "シンボリックリンクのiノード番号は参照元のファイルと必ず同じになる",
    ],
    correctIndex: 0,
    explanation:
      "ハードリンクは同一ファイルシステム内でのみiノードを共有して作成可能ですが、シンボリックリンクはファイルシステムをまたいで作成可能です。",
    difficulty: "advanced",
  },

  // ─── LPIC-1: シェルとスクリプト ─────────────────────────────────────
  {
    questionId: "q-lpic1-sh-01",
    cert: "lpic1",
    category: "シェルとスクリプト",
    text: "bashスクリプトの1行目に記述するシバン（shebang）の正しい書き方はどれか？",
    options: [
      "#!/bin/bash",
      "# /bin/bash",
      "// /bin/bash",
      "$!/bin/bash",
    ],
    correctIndex: 0,
    explanation:
      "スクリプト先頭の #! に続けてインタープリターのパス（#!/bin/bash）を記載します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-sh-02",
    cert: "lpic1",
    category: "シェルとスクリプト",
    text: "シェル変数を環境変数としてエクスポートし、子プロセスへ引き継ぐコマンドはどれか？",
    options: ["export", "set", "env-share", "inherit"],
    correctIndex: 0,
    explanation:
      "export 変数名=値 コマンドにより、設定された変数が環境変数となりシェルから起動する子プロセスでも利用可能になります。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-sh-03",
    cert: "lpic1",
    category: "シェルとスクリプト",
    text: "直前に実行したコマンドの終了ステータス（成功は0）が格納されている特殊なシェル変数はどれか？",
    options: ["$?", "$#", "$$", "$!"],
    correctIndex: 0,
    explanation:
      "$? には直前に実行したコマンドの戻り値（0なら成功、0以外はエラー）が保持されます。$#は引数の個数、$$は現在のプロセスIDを示します。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-sh-04",
    cert: "lpic1",
    category: "シェルとスクリプト",
    text: "bash スクリプトにおいて、条件判定 test -f /path/to/file が真になる条件はどれか？",
    options: [
      "指定したファイルが存在し、通常のファイルである場合",
      "指定したディレクトリが存在する場合",
      "ファイルが存在し、実行権限がある場合",
      "ファイルが空である場合",
    ],
    correctIndex: 0,
    explanation:
      "-f オプションは通常のファイルが存在するかを判定します（ディレクトリは -d、実行権限は -x、空ファイルは -s です）。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-sh-05",
    cert: "lpic1",
    category: "シェルとスクリプト",
    text: "ユーザーがログオンする際、システム全体で共通に読み込まれる初期化スクリプトファイルはどれか？",
    options: [
      "/etc/profile",
      "~/.bash_profile",
      "~/.bashrc",
      "/etc/skel/profile",
    ],
    correctIndex: 0,
    explanation:
      "ログインシェル起動時にはまずシステム共通の /etc/profile が実行され、その後ユーザー個別の ~/.bash_profile 等が処理されます。",
    difficulty: "advanced",
  },

  // ─── LPIC-1: ユーザーとセキュリティ ─────────────────────────────────
  {
    questionId: "q-lpic1-sec-01",
    cert: "lpic1",
    category: "ユーザーとセキュリティ",
    text: "ファイルの所有者と所有グループを同時に変更する chown コマンドの記述として正しいものはどれか？",
    options: [
      "chown user:group file.txt",
      "chown user-group file.txt",
      "chown user@group file.txt",
      "chgroup user:group file.txt",
    ],
    correctIndex: 0,
    explanation:
      "chown ユーザー名:グループ名 ファイル名（または ユーザー名.グループ名）の書式で所有者とグループを一度に変更できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-sec-02",
    cert: "lpic1",
    category: "ユーザーとセキュリティ",
    text: "数値によるパーミッション指定で「所有者に読み書き実行 (7)、グループに読み実行 (5)、その他に読み出しのみ (4)」を与える値は？",
    options: ["chmod 754 file.sh", "chmod 745 file.sh", "chmod 654 file.sh", "chmod 775 file.sh"],
    correctIndex: 0,
    explanation:
      "読み出し(r=4) + 書き込み(w=2) + 実行(x=1)の合計値から、所有者7、グループ5、その他4の chmod 754 となります。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-sec-03",
    cert: "lpic1",
    category: "ユーザーとセキュリティ",
    text: "umask値が 022 で設定されているシステムで、新規作成した一般ファイルのデフォルトパーミッションはどうなるか？",
    options: ["644 (-rw-r--r--)", "755 (-rwxr-xr-x)", "666 (-rw-rw-rw-)", "600 (-rw-------)"],
    correctIndex: 0,
    explanation:
      "通常のファイル作成時のベース権限 666 から umask 値 022 を差し引いた 644 (rw-r--r--) が適用されます。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-sec-04",
    cert: "lpic1",
    category: "ユーザーとセキュリティ",
    text: "ユーザーアカウントのハッシュ化されたパスワード文字列が保存されているセキュリティ上重要なファイルはどれか？",
    options: ["/etc/shadow", "/etc/passwd", "/etc/group", "/etc/gshadow"],
    correctIndex: 0,
    explanation:
      "/etc/passwd にはユーザー名やシェルパス等が記され、暗号化/ハッシュ化パスワードは root のみ読める /etc/shadow に格納されます。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-sec-05",
    cert: "lpic1",
    category: "ユーザーとセキュリティ",
    text: "sudo の設定ファイル /etc/sudoers を編集する際に、文法エラーによるロックアウトを防ぐために推奨される専用コマンドはどれか？",
    options: ["visudo", "sudoedit /etc/sudoers", "vi /etc/sudoers", "editsudo"],
    correctIndex: 0,
    explanation:
      "visudo コマンドは保存時に /etc/sudoers の文法テストを自動で実行し、構文エラーによる管理者権限喪失を未然に防ぎます。",
    difficulty: "advanced",
  },
  {
    questionId: "q-lpic1-sysarch-06",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "システムが稼働中の CPU 情報（モデル名、コア数、クロック数など）を確認するために読み出すべき仮想ファイルはどれか？",
    options: ["/proc/cpuinfo", "/proc/meminfo", "/proc/stat", "/sys/cpu/info"],
    correctIndex: 0,
    explanation: "/proc/cpuinfo ファイルを cat コマンド等で閲覧することで、現在稼働している CPU の型番やコア数・拡張命令セットなどを確認できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-sysarch-07",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "systemd 環境において、サービス「nginx.service」の現在の動作ステータスを確認するコマンドはどれか？",
    options: ["systemctl status nginx", "service status nginx", "systemctl show-status nginx", "systemd status nginx"],
    correctIndex: 0,
    explanation: "systemd 管理システムでサービスの動作状態や直近のログを確認するには systemctl status <サービス名> を使用します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-sysarch-08",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "カーネルモジュールをロードする際、依存関係（modules.dep）を自動的に解決してモジュールを組み込むコマンドはどれか？",
    options: ["modprobe", "insmod", "lsmod", "depmod"],
    correctIndex: 0,
    explanation: "modprobe コマンドは modules.dep ファイルを参照し、必要な依存モジュールをあわせて自動ロードします（insmod は単一モジュールのみ）。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-sysarch-09",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "systemd を使用するシステムにおいて、従来の「ランレベル 3（テキストログインのマルチユーザーモード）」に相当するターゲットはどれか？",
    options: ["multi-user.target", "graphical.target", "rescue.target", "runlevel3.target"],
    correctIndex: 0,
    explanation: "ランレベル 3 は multi-user.target、グラフィカルログイン環境（ランレベル 5）は graphical.target にそれぞれ対応します。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-sysarch-10",
    cert: "lpic1",
    category: "システムアーキテクチャ",
    text: "NVMe 接続SSDディスクの「1個目のドライブの2番目のパーティション」を表す正しいデバイス名はどれか？",
    options: ["/dev/nvme0n1p2", "/dev/nvme0p2", "/dev/sda2", "/dev/nvme1p2"],
    correctIndex: 0,
    explanation: "NVMeディスクは /dev/nvmeXnYpZ の形式を取り、0番目のコントローラ(0)の1番目のネームスペース(n1)の2番目のパーティション(p2)は /dev/nvme0n1p2 となります。",
    difficulty: "advanced",
  },
  {
    questionId: "q-lpic1-pkg-06",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "Debian/Ubuntu 系 Linux において、dpkg コマンドを使用して「インストール済みの全パッケージ」を一覧表示するオプションはどれか？",
    options: ["dpkg -l", "dpkg -L", "dpkg -s", "dpkg -i"],
    correctIndex: 0,
    explanation: "dpkg -l (-list) でインストール済みパッケージの一覧を、dpkg -L で指定パッケージがインストールしたファイル群を確認できます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-pkg-07",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "Red Hat/CentOS 系 Linux で、ある RPM パッケージが依存している共有ライブラリ等の要件を確認する正しいコマンドはどれか？",
    options: ["rpm -qR pkgname", "rpm -qa pkgname", "rpm -qf pkgname", "rpm -qi pkgname"],
    correctIndex: 0,
    explanation: "rpm -qR (Query Requires) オプションを使用することで、指定した RPM パッケージの動作に必要な依存要件を表示できます。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-pkg-08",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "dnf (yum) パッケージマネージャで、過去に実行されたインストールや削除等のトランザクション履歴を表示するコマンドはどれか？",
    options: ["dnf history", "dnf log", "dnf list-history", "dnf status"],
    correctIndex: 0,
    explanation: "dnf history (または yum history) コマンドを使うことで、過去のパッケージ更新履歴の確認や取り消し(undo)が可能になります。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-pkg-09",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "実行可能バイナリファイルが必要とする「動的リンク共有ライブラリ」を調査して一覧表示するコマンドはどれか？",
    options: ["ldd", "ldconfig", "nm", "objdump"],
    correctIndex: 0,
    explanation: "ldd コマンドを指定バイナリに対して実行すると、プログラムが依存する .so 共有ライブラリのパスを一覧表示できます。",
    difficulty: "advanced",
  },
  {
    questionId: "q-lpic1-pkg-10",
    cert: "lpic1",
    category: "パッケージ管理",
    text: "Debian/Ubuntu 系で、過去にダウンロードされキャッシュされた .deb パッケージファイルを完全に削除してディスク空き領域を確保するコマンドはどれか？",
    options: ["sudo apt clean", "sudo apt purge", "sudo apt remove", "sudo apt clear"],
    correctIndex: 0,
    explanation: "apt clean (または apt-get clean) は /var/cache/apt/archives に保管されている .deb キャッシュをすべて削除します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-cmd-06",
    cert: "lpic1",
    category: "基本コマンド",
    text: "拡張正規表現（ERE）を使用して文字パターンを検索する場合に、grep コマンドで指定すべきオプションはどれか？",
    options: ["grep -E", "grep -e", "grep -F", "grep -P"],
    correctIndex: 0,
    explanation: "grep -E (旧egrep相当) は + や ?、| 等の拡張正規表現をサポートします。なお grep -F は固定文字列検索(旧fgrep)です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-cmd-07",
    cert: "lpic1",
    category: "基本コマンド",
    text: "sed コマンドを使って、ファイル内のすべての文字列「old」を「new」に置換して標準出力する正しい書式はどれか？",
    options: ["sed 's/old/new/g' file", "sed 'r/old/new/g' file", "sed 's:old:new:1' file", "sed 'rep/old/new/' file"],
    correctIndex: 0,
    explanation: "sed の置換コマンド s と、行内全ての該当文字列を置換するフラグ g を組み合わせた 's/old/new/g' が標準的な書式です。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-cmd-08",
    cert: "lpic1",
    category: "基本コマンド",
    text: "スペース区切りされたテキストファイル data.txt の「1列目」と「3列目」を取り出して表示する正しい awk コマンドはどれか？",
    options: ["awk '{print $1, $3}' data.txt", "awk '{show 1, 3}' data.txt", "awk -F1,3 data.txt", "awk '{cut $1, $3}' data.txt"],
    correctIndex: 0,
    explanation: "awk では $1, $2... で各列を取り扱うことができ、print $1, $3 により指定列を出力できます。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-cmd-09",
    cert: "lpic1",
    category: "基本コマンド",
    text: "find コマンドで、ファイルサイズが「100MBより大きい」ファイルのみをルートディレクトリから検索する正しい指定はどれか？",
    options: ["find / -size +100M", "find / -size 100M", "find / -gt 100M", "find / --size >100M"],
    correctIndex: 0,
    explanation: "find でサイズ指定する場合は -size を用い、より大きいことを示す + と単位 M (または G) を組み合わせます。",
    difficulty: "advanced",
  },
  {
    questionId: "q-lpic1-cmd-10",
    cert: "lpic1",
    category: "基本コマンド",
    text: "コマンド A が「正常終了した場合のみ」続けてコマンド B を実行する、論理積を表す連結演算子はどれか？",
    options: ["&&", "||", ";", "&"],
    correctIndex: 0,
    explanation: "&& は前のコマンドが成功(終了コード0)した時のみ次を実行し、|| は前のコマンドが失敗した時のみ次を実行します。; は成否に関わらず順次実行します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-fs-06",
    cert: "lpic1",
    category: "ファイルシステムとデバイス",
    text: "システム起動時の自動マウント設定ファイル /etc/fstab には行ごとに 6 つのフィールドがあります。「3番目」のフィールドが表すものはどれか？",
    options: ["ファイルシステムの種類 (ext4, xfs, nfsなど)", "マウントポイント (/mnt/data など)", "マウントオプション (defaults など)", "ダンプフラグ"],
    correctIndex: 0,
    explanation: "/etc/fstab は「1:デバイス 2:マウントポイント 3:FS種類 4:オプション 5:dump 6:fsck」の 6 項目から構成されます。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-fs-07",
    cert: "lpic1",
    category: "ファイルシステムとデバイス",
    text: "パーティション /dev/sdb1 に ext4 ファイルシステムを作成（フォーマット）するコマンドはどれか？",
    options: ["mkfs.ext4 /dev/sdb1", "fdisk.ext4 /dev/sdb1", "format -t ext4 /dev/sdb1", "mkpart ext4 /dev/sdb1"],
    correctIndex: 0,
    explanation: "ファイルシステム作成コマンドは mkfs.<FS種別> <デバイス名> または mkfs -t <FS種別> <デバイス名> を使用します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-fs-08",
    cert: "lpic1",
    category: "ファイルシステムとデバイス",
    text: "ディスクブロック自体の空き容量は十分あるにもかかわらず「No space left on device」とエラーになる場合、i ノードの枯渇を調べるコマンドはどれか？",
    options: ["df -i", "du -i", "ls -i", "fdisk -l"],
    correctIndex: 0,
    explanation: "df -i オプションを指定することで、ファイルシステムごとの i ノード総数と現在の使用数・残量を確認できます。",
    difficulty: "advanced",
  },
  {
    questionId: "q-lpic1-fs-09",
    cert: "lpic1",
    category: "ファイルシステムとデバイス",
    text: "ディレクトリ「/var/log」自体の合計ディスク使用量のみを、人間が読みやすい単位（MBやGB等）で表示するコマンドはどれか？",
    options: ["du -sh /var/log", "du -ah /var/log", "df -h /var/log", "ls -sh /var/log"],
    correctIndex: 0,
    explanation: "du (Disk Usage) コマンドで合計のみ(-s)と単位付き(-h)を組み合わせた du -sh はディレクトリー容量確認の定番です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-fs-10",
    cert: "lpic1",
    category: "ファイルシステムとデバイス",
    text: "新しく作成したスワップパーティション /dev/sdc2 を、システムでただちに有効化するコマンドはどれか？",
    options: ["swapon /dev/sdc2", "mkswap /dev/sdc2", "mount -t swap /dev/sdc2", "enable-swap /dev/sdc2"],
    correctIndex: 0,
    explanation: "mkswap で初期化した後、swapon コマンドを実行することでスワップ領域が即座に仮想メモリとして有効になります。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-sh-06",
    cert: "lpic1",
    category: "シェルとスクリプト",
    text: "システム全体のユーザー全員に共通する環境変数やパス設定を記載するグローバルな設定ファイルはどれか？",
    options: ["/etc/profile", "~/.bashrc", "~/.profile", "/etc/skel"],
    correctIndex: 0,
    explanation: "/etc/profile はログインシェル起動時に最初に読み込まれるシステム共通設定ファイルです。~/.bashrc は個人ユーザー用です。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-sh-07",
    cert: "lpic1",
    category: "シェルとスクリプト",
    text: "直前に実行したコマンドがエラーで終了したか成功したかを表す「終了ステータス（戻り値）」が格納されている特殊変数はどれか？",
    options: ["$?", "$#", "$$", "$!"],
    correctIndex: 0,
    explanation: "$? には直前のコマンドの終了ステータス（0:正常、0以外:エラー）が格納されます。なお $# は引数の数、$$ は自身のPIDです。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-sh-08",
    cert: "lpic1",
    category: "シェルとスクリプト",
    text: "コマンド「ll」を入力した際に「ls -la」が実行されるように、シェルのエイリアスを設定する正しい記述はどれか？",
    options: ["alias ll='ls -la'", "set alias ll='ls -la'", "export ll='ls -la'", "alias ll 'ls -la'"],
    correctIndex: 0,
    explanation: "alias コマンドは = の両辺にスペースを空けず alias 名前='コマンド' の文法でエイリアスを定義します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-sh-09",
    cert: "lpic1",
    category: "シェルとスクリプト",
    text: "シェルスクリプト中で複数行の文字列を EOF という文字列が現れるまで標準入力として流し込む機能（ヒアドキュメント）を表す記号はどれか？",
    options: ["<< EOF", ">> EOF", "< EOF", "|| EOF"],
    correctIndex: 0,
    explanation: "<< 終了識別子（例: << EOF）を用いることで、スクリプト内の複数行テキストをコマンドの入力としてまとめることができます。",
    difficulty: "advanced",
  },
  {
    questionId: "q-lpic1-sh-10",
    cert: "lpic1",
    category: "シェルとスクリプト",
    text: "コマンド実行時の「標準エラー出力(2)」を「標準出力(1)」と同じ出力先にマージしてリダイレクトする正しい記法はどれか？",
    options: ["2>&1", "1>&2", "2>>1", "&2>1"],
    correctIndex: 0,
    explanation: "2>&1 はファイル記述子 2 (標準エラー) をファイル記述子 1 (標準出力) の向かう先へとリダイレクト・結合する必須文法です。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-sec-06",
    cert: "lpic1",
    category: "ユーザーとセキュリティ",
    text: "ユーザーパスワードのハッシュ値および有効期限情報（パスワードエイジング）が保持される管理ファイルはどれか？",
    options: ["/etc/shadow", "/etc/passwd", "/etc/group", "/etc/login.defs"],
    correctIndex: 0,
    explanation: "/etc/shadow は一般ユーザーからの閲覧が制限され、安全にパスワードハッシュや更新期限を格納しています。",
    difficulty: "beginner",
  },
  {
    questionId: "q-lpic1-sec-07",
    cert: "lpic1",
    category: "ユーザーとセキュリティ",
    text: "新規ユーザー「taro」を作成する際、ホームディレクトリを自動作成しつつログインシェルを /bin/bash に指定するコマンドはどれか？",
    options: ["useradd -m -s /bin/bash taro", "useradd -h -l /bin/bash taro", "adduser --shell /bin/bash --no-home taro", "newuser -d -s /bin/bash taro"],
    correctIndex: 0,
    explanation: "useradd コマンドでホーム作成を指定する -m オプションと、シェルを指定する -s オプションを組み合わせます。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-sec-08",
    cert: "lpic1",
    category: "ユーザーとセキュリティ",
    text: "実行時に「ファイル所有者の権限」でプロセスが動作する SUID (Set-User-ID) ビットを、chmod で数値モード設定する値はどれか？",
    options: ["chmod 4755", "chmod 2755", "chmod 1755", "chmod 7755"],
    correctIndex: 0,
    explanation: "特殊パーミッションにおいて 4 は SUID、2 は SGID、1 はスティッキービットを表し、4755 のように先頭に付与します。",
    difficulty: "advanced",
  },
  {
    questionId: "q-lpic1-sec-09",
    cert: "lpic1",
    category: "ユーザーとセキュリティ",
    text: "/tmp ディレクトリのように「誰でも書き込めるが、自分が作成したファイルしか削除できない」属性（スティッキービット）を表す権限表記はどれか？",
    options: ["rwxrwxrwt", "rwsrwxrwx", "rwxrwsrwx", "rwxrwxrwx"],
    correctIndex: 0,
    explanation: "スティッキービットが有効になるとその他ユーザーの実行ビットが t または T と表記され、他ユーザーのファイル削除を防止します。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-lpic1-sec-10",
    cert: "lpic1",
    category: "ユーザーとセキュリティ",
    text: "現在ログイン中のユーザーが設定されている所属グループ情報を一覧表示する基本コマンドはどれか？",
    options: ["groups", "whoami", "id -u", "showgroup"],
    correctIndex: 0,
    explanation: "groups または id -G コマンドを実行することで、ユーザーが所属するすべての主グループ・補助グループを確認できます。",
    difficulty: "beginner",
  },

  // ─── CCNA: ネットワーク基礎 ─────────────────────────────────────────
  {
    questionId: "q-ccna-net-01",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "OSI参照モデルにおいて、ルーターがIPアドレスを用いてパケットの宛先経路選択を行う階層はどれか？",
    options: ["ネットワーク層（第3層）", "データリンク層（第2層）", "トランスポート層（第4層）", "物理層（第1層）"],
    correctIndex: 0,
    explanation:
      "ルーターはOSI参照モデルのネットワーク層（第3層・L3）に位置し、IPヘッダ情報を見て最適なルーティングを行います。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-net-02",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "TCPとUDPの違いについて正しい記述はどれか？",
    options: [
      "TCPはコネクション型で信頼性が高く、UDPはコネクションレス型で高速・低遅延である",
      "UDPは3ウェイハンドシェイクにより通信の確立を確認する",
      "TCPは音声通話(VoIP)やストリーミング動画でのみ主に使用される",
      "UDPはパケット順序の並び替えや再送制御を標準で行う",
    ],
    correctIndex: 0,
    explanation:
      "TCPは3ウェイハンドシェイクや再送制御により高い信頼性を保証し、UDPはそれらを省くことでリアルタイム性や高速性を重視します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-net-03",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "IPv4アドレスにおいて、クラスCのデフォルトサブネットマスク（プレフィックス長）はどれか？",
    options: ["255.255.255.0 (/24)", "255.255.0.0 (/16)", "255.0.0.0 (/8)", "255.255.255.255 (/32)"],
    correctIndex: 0,
    explanation:
      "クラスCアドレス（192.0.0.0〜223.255.255.255）の標準サブネットマスクは 255.255.255.0 (/24) です。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-net-04",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "宛先IPアドレスから対応するMACアドレスを解決するために送信されるプロトコルはどれか？",
    options: ["ARP", "ICMP", "DNS", "DHCP"],
    correctIndex: 0,
    explanation:
      "ARP (Address Resolution Protocol) は宛先IPアドレスをもとに同一LAN内のMACアドレスを問い合わせます。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-net-05",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "IPv6アドレスの中で、同一リンク内でのみ有効となる「リンクローカルアドレス」のプレフィックスはどれか？",
    options: ["fe80::/10", "fc00::/7", "ff00::/8", "2001::/16"],
    correctIndex: 0,
    explanation:
      "fe80::/10 で始まるアドレスはリンクローカルアドレスであり、ルーターを越えない同一セグメント内でのみ使用されます。",
    difficulty: "advanced",
  },

  // ─── CCNA: スイッチング・VLAN ──────────────────────────────────────
  {
    questionId: "q-ccna-sw-01",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "複数のVLANフレームにタグを付けて1本の物理ポートで転送する規格として最も標準的なものはどれか？",
    options: ["IEEE 802.1Q", "IEEE 802.1X", "IEEE 802.11", "IEEE 802.3ad"],
    correctIndex: 0,
    explanation:
      "IEEE 802.1Q はイーサネットフレームに4バイトのVLANタグ（VLAN ID 等）を挿入する業界標準のトランクプロトコルです。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-sw-02",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "スイッチのポートにおいて、PCやサーバなど単一端末を接続し、一つのVLANにのみ所属させるモードはどれか？",
    options: ["アクセスポート", "トランクポート", "ダイナミックポート", "コンソールポート"],
    correctIndex: 0,
    explanation:
      "アクセスポート（switchport mode access）は特定の1つのVLANにのみ所属し、タグなしフレームを送受信します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-sw-03",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "ループ構成においてブロードキャストストームを防ぐため、冗長経路の一方を自動ブロックするプロトコルは？",
    options: ["STP (Spanning Tree Protocol)", "LACP", "VTP", "CDP"],
    correctIndex: 0,
    explanation:
      "STP（または RSTP）はネットワーク内のループを検知して一部のポートをブロッキング状態にし、論理的にループのないツリー構成を維持します。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-sw-04",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "Cisco Catalyst スイッチで VLAN 10 と VLAN 20 を作成するための基本的な設定コマンド順序はどれか？",
    options: [
      "vlan 10 -> vlan 20",
      "switchport access vlan 10,20",
      "vlan database create 10 20",
      "interface vlan 10-20",
    ],
    correctIndex: 0,
    explanation:
      "グローバルコンフィギュレーションモードから vlan 10 で作成し、続けて vlan 20 を作成するのが標準書式です。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-sw-05",
    cert: "ccna",
    category: "スイッチング・VLAN",
    text: "STPにおける「PortFast」機能の主な役割として正しいものはどれか？",
    options: [
      "リスニングおよびラーニング状態をスキップし、ただちにフォワーディング状態へ移行する",
      "スイッチ間でのBPDU交換を高速化する",
      "ポートのリンク速度を100Mbpsから10Gbpsに自動拡張する",
      "トランクポート上のVLANタグ付け処理を不要にする",
    ],
    correctIndex: 0,
    explanation:
      "PortFast はエンド端末接続ポートにおいてSTPのリスニング/ラーニング待機（約30秒）を省略し、即時フォワーディングに移行させる機能です。",
    difficulty: "advanced",
  },

  // ─── CCNA: IPルーティング ─────────────────────────────────────────
  {
    questionId: "q-ccna-rt-01",
    cert: "ccna",
    category: "IPルーティング",
    text: "Cisco ルーターにおいて、デフォルトルート（すべての宛先へのスタティックルート）の設定コマンドはどれか？",
    options: [
      "ip route 0.0.0.0 0.0.0.0 ネクストホップIP",
      "ip default-route 0.0.0.0 0.0.0.0",
      "route default 0.0.0.0",
      "ip gateway 0.0.0.0",
    ],
    correctIndex: 0,
    explanation:
      "ip route 0.0.0.0 0.0.0.0 <次のルーターIPまたはインターフェース> により、ルーティングテーブルに該当がない宛先のデフォルト経路を設定します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-rt-02",
    cert: "ccna",
    category: "IPルーティング",
    text: "ルーティングプロトコル OSPF（Open Shortest Path First）の基本的な特徴として正しいものはどれか？",
    options: [
      "リンクステート型であり、コスト（帯域幅ベース）を指標に最短経路を計算する",
      "ディスタンスベクター型であり、ホップ数のみで経路を計算する",
      "アドミニストレーティブディスタンス（AD値）は標準で120である",
      "ルーター間で15ホップを超える経路を設定できない",
    ],
    correctIndex: 0,
    explanation:
      "OSPF はリンクステート型アルゴリズム（Dijkstra）を採用し、リンクのコスト（10^8/帯域幅）を指標とした高速・安定なルーティングを行います。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-rt-03",
    cert: "ccna",
    category: "IPルーティング",
    text: "異なるルーティングソース（静的やOSPF等）から同一宛先を学習した際、ルーターが優先順位の判断に用いる指標はどれか？",
    options: [
      "アドミニストレーティブディスタンス (AD値)",
      "メトリック値",
      "MTU値",
      "ホップカウント",
    ],
    correctIndex: 0,
    explanation:
      "AD値（Administrative Distance）はルーティング情報源の信頼性（小ささ重視: Static=1, EIGRP=90, OSPF=110等）を比較して採用経路を決定します。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-rt-04",
    cert: "ccna",
    category: "IPルーティング",
    text: "ルーターがパケットを転送する際、ルーティングテーブル内で最も一致するビット数が長い経路を優先するルールを何と呼ぶか？",
    options: [
      "ロンゲストマッチ（最長一致）ルール",
      "ショートパスファースト",
      "イコールコストマルチパス",
      "デフォルトフォワード",
    ],
    correctIndex: 0,
    explanation:
      "ロンゲストマッチにより、10.0.0.0/8 より 10.1.1.0/24 など、よりプレフィックス長が長く具体的（詳細）に一致する経路が最優先で採用されます。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-rt-05",
    cert: "ccna",
    category: "IPルーティング",
    text: "OSPFでルーターIDを明示的に指定していない場合、自動決定される順序として最優先されるものはどれか？",
    options: [
      "ループバックインターフェースの中で最大（最も高い）IPアドレス",
      "物理インターフェースの中で最も低いIPアドレス",
      "MACアドレスの中で最大の数値",
      "最初に起動したインターフェースのIPアドレス",
    ],
    correctIndex: 0,
    explanation:
      "OSPF ルーターIDの決定順位: ① router-id 設定値 > ② ループバックIF中の最大IP > ③ アクティブな物理IF中の最大IP となります。",
    difficulty: "advanced",
  },

  // ─── CCNA: IPサービス ─────────────────────────────────────────
  {
    questionId: "q-ccna-svc-01",
    cert: "ccna",
    category: "IPサービス",
    text: "社内LANのプライベートIPアドレスを、インターネット接続時に単一のグローバルIPアドレスの異なるポート番号へ変換する技術はどれか？",
    options: ["PAT (NAPT / IPマスカレード)", "スタティックNAT", "ダイナミックNAT", "DHCPリレー"],
    correctIndex: 0,
    explanation:
      "PAT (Port Address Translation) は送信元ポート番号を区別することで、複数のプライベートIPアドレスを1個のグローバルIPで共有してインターネット接続させます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-svc-02",
    cert: "ccna",
    category: "IPサービス",
    text: "ネットワーク内のルーターやサーバの時刻を正確に同期させるために使用されるプロトコルはどれか？",
    options: ["NTP (Network Time Protocol)", "SNMP", "DHCP", "DNS"],
    correctIndex: 0,
    explanation:
      "NTP はUDPポート123番を使用し、タイムサーバから正確な時刻を取得してログ分析やセキュリティ証明書の正確な検証に役立ちます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-svc-03",
    cert: "ccna",
    category: "IPサービス",
    text: "DHCPクライアントがIPアドレスを割り当ててもらう際、最初にブロードキャスト送信するメッセージはどれか？",
    options: [
      "DHCP DISCOVER",
      "DHCP OFFER",
      "DHCP REQUEST",
      "DHCP ACK",
    ],
    correctIndex: 0,
    explanation:
      "DHCPの通信手順(DORA): ① DISCOVER(探索) → ② OFFER(提供) → ③ REQUEST(要求) → ④ ACK(承認) の順序で行われます。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-svc-04",
    cert: "ccna",
    category: "IPサービス",
    text: "ネットワーク機器のCPU使用率やインターフェース状態を収集し、監視するために使用される標準プロトコルはどれか？",
    options: ["SNMP (Simple Network Management Protocol)", "Syslog", "NetFlow", "CDP"],
    correctIndex: 0,
    explanation:
      "SNMP はマネージャとエージェント間で MIB 情報を収集・監視し、トラブル通知である Trap の受信などを実現します。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-svc-05",
    cert: "ccna",
    category: "IPサービス",
    text: "Cisco 機器で Syslog サーバー（192.168.1.100）へログを送信するための設定コマンドはどれか？",
    options: [
      "logging host 192.168.1.100",
      "syslog server 192.168.1.100",
      "log-target 192.168.1.100",
      "logging server 192.168.1.100",
    ],
    correctIndex: 0,
    explanation:
      "グローバルコンフィギュレーションモードで logging host <SyslogサーバのIP> コマンドを設定することで外部サーバへログが転送されます。",
    difficulty: "advanced",
  },

  // ─── CCNA: セキュリティ基礎 ─────────────────────────────────────────
  {
    questionId: "q-ccna-sec-01",
    cert: "ccna",
    category: "セキュリティ基礎",
    text: "標準アクセス制御リスト（標準ACL: 番号1〜99）がパケットをフィルタリングする判断基準とする情報はどれか？",
    options: [
      "送信元IPアドレスのみ",
      "送信元IPアドレスと宛先IPアドレス",
      "送信元・宛先のIPアドレスとポート番号",
      "MACアドレス",
    ],
    correctIndex: 0,
    explanation:
      "標準ACL（番号1〜99または1300〜1999）はパケットの「送信元IPアドレス」のみに基づいて許可・拒否の判定を行います。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-sec-02",
    cert: "ccna",
    category: "セキュリティ基礎",
    text: "スイッチのポートセキュリティにおいて、不正なMACアドレスを検知した際にデフォルトで適用される違反アクションはどれか？",
    options: ["Shutdown（ポートのエラー無効化）", "Protect（パケット破棄のみ）", "Restrict（破棄およびSyslog通知）", "Warning"],
    correctIndex: 0,
    explanation:
      "ポートセキュリティの標準動作（violation mode shutdown）では、不正アクセス検知時にインターフェースが err-disabled（シャットダウン）状態になります。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-sec-03",
    cert: "ccna",
    category: "セキュリティ基礎",
    text: "拡張アクセス制御リスト（拡張ACL: 番号100〜199）を適用する場所の設計原則として最もベストプラクティスなのはどれか？",
    options: [
      "送信元（トラフィックの発生源）にできるだけ近い場所",
      "宛先（ターゲットサーバ）にできるだけ近い場所",
      "ネットワークの中央コアスイッチのみ",
      "インターネットゲートウェイの出口のみ",
    ],
    correctIndex: 0,
    explanation:
      "拡張ACLは送信元・宛先・ポート番号を判別できるため、不要なパケットを無駄にネットワーク内へ流さないよう送信元に近い場所への配置が基本です。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-sec-04",
    cert: "ccna",
    category: "セキュリティ基礎",
    text: "「DHCPスヌーピング」機能の主なセキュリティ上の役割はどれか？",
    options: [
      "信頼できないポートからの悪意あるDHCPサーバ応答（攻撃メッセージ）を遮断する",
      "DHCPパケットを自動で暗号化する",
      "ルーターのCPU負荷を軽減するためにDHCPを停止する",
      "固定IPアドレスの端末のみをLANに接続させる",
    ],
    correctIndex: 0,
    explanation:
      "DHCPスヌーピングはポートを信頼ポート(Trusted)と非信頼ポート(Untrusted)に分け、正規のDHCPサーバポート以外からの不正応答をシャットアウトします。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-sec-05",
    cert: "ccna",
    category: "セキュリティ基礎",
    text: "ネットワーク認証における「AAA」の3つの要素として正しい組み合わせはどれか？",
    options: [
      "Authentication (認証) / Authorization (認可) / Accounting (課金・ログ)",
      "Access / Administration / Audit",
      "Address / Authority / Alert",
      "Advanced / Application / Security",
    ],
    correctIndex: 0,
    explanation:
      "AAA は Authentication(本人確認)・Authorization(権限付与)・Accounting(利用履歴保存)の頭文字で、RADIUSやTACACS+等で使用されるセキュリティ概念です。",
    difficulty: "advanced",
  },

  // ─── CCNA: 自動化とプログラマビリティ ─────────────────────────────────
  {
    questionId: "q-ccna-auto-01",
    cert: "ccna",
    category: "自動化とプログラマビリティ",
    text: "REST API において、リソースの新規作成やデータ送信に使用される標準的な HTTP メソッドはどれか？",
    options: ["POST", "GET", "PUT", "DELETE"],
    correctIndex: 0,
    explanation:
      "REST API において、GET は取得、POST は新規作成・処理要求、PUT/PATCH は更新、DELETE は削除に使用されます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-auto-02",
    cert: "ccna",
    category: "自動化とプログラマビリティ",
    text: "JSON（JavaScript Object Notation）のキーと値のペアを定義する正しい記述例はどれか？",
    options: [
      '{"hostname": "Router-A", "ip": "192.168.1.1"}',
      '<hostname>Router-A</hostname>',
      'hostname = "Router-A"',
      '{hostname: Router-A}',
    ],
    correctIndex: 0,
    explanation:
      "JSON のプロパティ名（キー）と文字列値は必ずダブルクォートで囲み、コロン（:）で結びます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-auto-03",
    cert: "ccna",
    category: "自動化とプログラマビリティ",
    text: "エージェントレス構造（SSH経由）でYAML形式の Playbook を用いて構成管理や自動化を行うツールはどれか？",
    options: ["Ansible", "Puppet", "Chef", "Docker"],
    correctIndex: 0,
    explanation:
      "Ansible は管理対象機器に専用エージェントをインストールせず、SSH と YAML 形式の Playbook で自動設定を行います。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-auto-04",
    cert: "ccna",
    category: "自動化とプログラマビリティ",
    text: "SDN（Software Defined Networking）において、コントローラーが下位のスイッチやルーターを制御する通信インタフェースを何と呼ぶか？",
    options: ["Southbound API", "Northbound API", "Eastbound API", "Westbound API"],
    correctIndex: 0,
    explanation:
      "SDNコントローラーとネットワーク機器間を繋ぐインターフェースは Southbound API（OpenFlow や NETCONF 等）、アプリケーションとの接続は Northbound API と呼ばれます。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-auto-05",
    cert: "ccna",
    category: "自動化とプログラマビリティ",
    text: "REST API のレスポンスコードにおいて「認証失敗または認証トークン不正（Unauthorized）」を表すステータスコードはどれか？",
    options: ["401 Unauthorized", "403 Forbidden", "404 Not Found", "500 Internal Server Error"],
    correctIndex: 0,
    explanation:
      "HTTPステータスコード 401 は認証エラー（Unauthorized）、403 は権限不足（Forbidden）を示します。",
    difficulty: "advanced",
  },
  {
    questionId: "q-ccna-net-06",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "TCP において信頼性の高い通信を開始する際に行われる「3ウェイハンドシェイク」の正しいパケット順序はどれか？",
    options: ["SYN → SYN/ACK → ACK", "SYN → ACK → SYN/ACK", "ACK → SYN → SYN/ACK", "SYN/ACK → SYN → ACK"],
    correctIndex: 0,
    explanation: "TCP 接続確立は、送信元からの SYN、送信先からの SYN/ACK、送信元からの ACK の 3 ステップで行われます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-net-07",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "UDP (User Datagram Protocol) の特徴として「誤っている」ものはどれか？",
    options: ["順序制御や再送制御を行い、通信の確実性を保証する", "コネクションレス型の通信プロトコルである", "TCPに比べてオーバーヘッドが小さく遅延が少ない", "VoIP や音声・動画ストリーミングに適している"],
    correctIndex: 0,
    explanation: "順序制御や再送制御により信頼性を保証するのは TCP の特徴です。UDP は信頼性よりもリアルタイム性を優先します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-net-08",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "同じサブネット内の通信相手の「IP アドレス」から「MAC アドレス」を解決するために使用されるプロトコルはどれか？",
    options: ["ARP", "DNS", "DHCP", "ICMP"],
    correctIndex: 0,
    explanation: "ARP (Address Resolution Protocol) は、ターゲットの IP アドレスに対する MAC アドレスをブロードキャスト照会で解決します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-net-09",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "RFC 1918 で定義されている IPv4 プライベートアドレス空間の記述として、正しいブロックはどれか？",
    options: ["172.16.0.0/12 (172.16.0.0 ～ 172.31.255.255)", "172.16.0.0/16 (172.16.0.0 ～ 172.16.255.255)", "192.168.0.0/24", "10.0.0.0/16"],
    correctIndex: 0,
    explanation: "クラスBのプライベートIP範囲は 172.16.0.0/12 (172.16.0.0～172.31.255.255) です。クラスAは 10.0.0.0/8、クラスCは 192.168.0.0/16 です。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-net-10",
    cert: "ccna",
    category: "ネットワーク基礎",
    text: "プレフィックス長「/26 (255.255.255.192)」のサブネットにおいて、ホストに割り当て可能な有効 IP アドレス数はいくつか？",
    options: ["62", "64", "60", "126"],
    correctIndex: 0,
    explanation: "ホストビットが 6 ビットあるため、総数は 2^6 = 64 個です。ネットワークアドレスとブロードキャストアドレスを除く 62 個が有効アドレスとなります。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-sw-06",
    cert: "ccna",
    category: "ネットワークアクセス",
    text: "IEEE 802.1Q トランキングにおいて、フレームのイーサネットヘッダ内に挿入される VLAN タグのサイズは何バイトか？",
    options: ["4 バイト", "2 バイト", "8 バイト", "64 バイト"],
    correctIndex: 0,
    explanation: "IEEE 802.1Q では送信元 MAC の直後に 4 バイト（TPID や TCI/VLAN ID を含む）のタグフィールドを挿入します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-sw-07",
    cert: "ccna",
    category: "ネットワークアクセス",
    text: "Cisco Catalyst スイッチの MAC アドレスアドレステーブルにおけるデフォルトの「エージングタイム（保持時間）」はいくつか？",
    options: ["300 秒 (5分)", "60 秒 (1分)", "600 秒 (10分)", "3600 秒 (1時間)"],
    correctIndex: 0,
    explanation: "Cisco スイッチでは学習した MAC アドレスをデフォルトで 300 秒（5分間）保持します。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-sw-08",
    cert: "ccna",
    category: "ネットワークアクセス",
    text: "DTP (Dynamic Trunking Protocol) モードにおいて、対向ポートが dynamic auto であった場合、トランクが確立する設定はどれか？",
    options: ["dynamic desirable または trunk", "dynamic auto", "access", "nonegotiate"],
    correctIndex: 0,
    explanation: "dynamic auto どうしでは受動的であるためトランクは確立しません。能動的に交渉する dynamic desirable または手動の trunk が必要です。",
    difficulty: "advanced",
  },
  {
    questionId: "q-ccna-sw-09",
    cert: "ccna",
    category: "ネットワークアクセス",
    text: "STP (Spanning Tree Protocol) において、ルートブリッジを選出する際に「最初に」比較される基準はどれか？",
    options: ["ブリッジプライオリティ値 (最小のものが優先)", "MAC アドレス (最大のものが優先)", "ポートコスト (最小のものが優先)", "インターフェース番号"],
    correctIndex: 0,
    explanation: "ブリッジ ID はプライオリティ値と MAC アドレスから構成され、まずプライオリティ値（デフォルト 32768）が最も低い機器が優先されます。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-sw-10",
    cert: "ccna",
    category: "ネットワークアクセス",
    text: "EtherChannel (リンクアグリゲーション) を構成するネゴシエーションプロトコルのうち、IEEE 標準プロトコルはどれか？",
    options: ["LACP (IEEE 802.3ad / 802.1AX)", "PAgP (Cisco 独自)", "VTP", "DTP"],
    correctIndex: 0,
    explanation: "LACP (Link Aggregation Control Protocol) は IEEE の業界標準規格であり、他社メーカーとの機器間でもバンドルが可能です。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-rt-06",
    cert: "ccna",
    category: "IPコネクティビティ",
    text: "OSPF におけるルーターID (Router ID) の選出基準として、手動で router-id コマンドが設定されていない場合、次に優先されるものはどれか？",
    options: ["アクティブなループバックインターフェースの中で最大の IP アドレス", "アクティブな物理インターフェースの中で最小の IP アドレス", "MAC アドレスが最も小さい物理ポート", "インターフェース帯域幅が最大のもの"],
    correctIndex: 0,
    explanation: "OSPFルーターIDは「1: 手動指定 > 2: 最大ループバックIP > 3: 最大物理インターフェースIP」の順で決定されます。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-rt-07",
    cert: "ccna",
    category: "IPコネクティビティ",
    text: "ルーターがパケットを転送する際、ルーティングテーブル内に複数の適合する宛先がある場合に選択される「ロンゲストマッチ原則」の説明はどれか？",
    options: ["プレフィックス長（サブネットマスク）のビット数が最も長い経路を優先する", "AD (アドミニストレーティブディスタンス) 値が最も高い経路を優先する", "メトリック値が最も大きい経路を優先する", "最も新しく学習された経路を優先する"],
    correctIndex: 0,
    explanation: "ロンゲストマッチ（最長一致）原則では、/24 より /28 など、宛先IPに対して最も具体的に一致するビット数の長いルートを最優先で選択します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-rt-08",
    cert: "ccna",
    category: "IPコネクティビティ",
    text: "メイン回線に OSPF が動いている環境で、バックアップ回線用のスタティックルートを「通常時は使われず障害時のみ動く」フローティングスタティックにする設定はどれか？",
    options: ["ip route 0.0.0.0 0.0.0.0 10.0.0.2 130", "ip route 0.0.0.0 0.0.0.0 10.0.0.2 100", "ip route 0.0.0.0 0.0.0.0 10.0.0.2 1", "ip route 0.0.0.0 0.0.0.0 10.0.0.2 0"],
    correctIndex: 0,
    explanation: "OSPFのデフォルトAD値は110です。これよりも大きいAD値（例: 130）をスタティックルートの後ろに指定することでバックアップ経路になります。",
    difficulty: "advanced",
  },
  {
    questionId: "q-ccna-rt-09",
    cert: "ccna",
    category: "IPコネクティビティ",
    text: "マルチエリア OSPF 環境において、バックボーンエリア（Area 0）と他のエリアを接続する役割を持つルーターの呼称はどれか？",
    options: ["ABR (Area Border Router)", "ASBR (Autonomous System Boundary Router)", "DR (Designated Router)", "IR (Internal Router)"],
    correctIndex: 0,
    explanation: "複数のOSPFエリアの境界に立ち、エリア間の経路情報を要約して交換するルーターを ABR (エリア境界ルーター) と呼びます。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-rt-10",
    cert: "ccna",
    category: "IPコネクティビティ",
    text: "Cisco ルーターの「show ip route」出力において、コード表記「S*」が意味するものはどれか？",
    options: ["デフォルトのスタティックルート (候補デフォルト)", "OSPF によって学習された外部ルート", "EIGRP によるバックアップサクセサ", "直接接続されているローカルインターフェース"],
    correctIndex: 0,
    explanation: "「S」はスタティックルート、「*」はデフォルトルート候補を意味し、合わせて「デフォルトスタティックルート」を示します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-svc-06",
    cert: "ccna",
    category: "IPサービス",
    text: "Cisco ルーターの NAT 設定において、内部ネットワークのホストが「外部（インターネット）から見て変換されている IP アドレス」を何と呼ぶか？",
    options: ["Inside Global (内部グローバル) アドレス", "Inside Local (内部ローカル) アドレス", "Outside Local (外部ローカル) アドレス", "Outside Global (外部グローバル) アドレス"],
    correctIndex: 0,
    explanation: "内部端末(Inside Local)がルーターでNAT変換された後のグローバル側IPは「Inside Global」と呼ばれます。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-svc-07",
    cert: "ccna",
    category: "IPサービス",
    text: "DHCP サーバーが異なるサブネットに配置されている場合、クライアントからのブロードキャスト要求をユニキャストに変換して転送する設定コマンドはどれか？",
    options: ["ip helper-address <DHCPサーバーのIP>", "ip dhcp relay <DHCPサーバーのIP>", "ip forward-broadcast", "ip dhcp-server <DHCPサーバーのIP>"],
    correctIndex: 0,
    explanation: "ルーターのインターフェースコンフィグモードで ip helper-address コマンドを設定することで DHCP リレーエージェントとして動作します。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-svc-08",
    cert: "ccna",
    category: "IPサービス",
    text: "NTP (Network Time Protocol) の正確さの指標を表す「Stratum（ストラタム）」において、最上位の基準時刻源（原子時計やGPS）に直接接続されているサーバーのレベルはどれか？",
    options: ["Stratum 1", "Stratum 0", "Stratum 2", "Stratum 16"],
    correctIndex: 0,
    explanation: "原子時計やGPS自身が Stratum 0 であり、それに直接接続して正確な時刻を配信する NTP サーバーが Stratum 1 になります。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-svc-09",
    cert: "ccna",
    category: "IPサービス",
    text: "SNMP (Simple Network Management Protocol) のバージョンのうち、「ユーザー認証」および通信の「暗号化 (DES/AES)」を両方サポートするバージョンはどれか？",
    options: ["SNMPv3", "SNMPv2c", "SNMPv1", "SNMPv2u"],
    correctIndex: 0,
    explanation: "SNMPv1 と SNMPv2c はコミュニティ名（クリアテキスト）認証のみですが、SNMPv3 は暗号化(priv)と高度なユーザー認証(auth)に対応しています。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-svc-10",
    cert: "ccna",
    category: "IPサービス",
    text: "Syslog メッセージをルーターが送信する際、ログメッセージに「正確なタイムスタンプ」を含めるために必要な設定はどれか？",
    options: ["service timestamps log datetime msec", "logging timestamp enable", "syslog time-format full", "service syslog-time on"],
    correctIndex: 0,
    explanation: "Cisco 機器では service timestamps log datetime msec (または localtime) によりログ出力にミリ秒精度のタイムスタンプを付加します。",
    difficulty: "advanced",
  },
  {
    questionId: "q-ccna-sec-06",
    cert: "ccna",
    category: "セキュリティ基礎",
    text: "ポートセキュリティの設定で違反モードを「restrict」にした場合の動作特徴として正しいものはどれか？",
    options: ["違反フレームを破棄し、Syslog/SNMPトラップを送信して違反カウンタを増加させる（ポートはシャットダウンしない）", "ポートをすぐに error-disabled 状態にしてシャットダウンする", "違反フレームを破棄するだけでログ出力やカウンタ増加を行わない", "すべてのトラフィックを無条件に許可しログのみを保存する"],
    correctIndex: 0,
    explanation: "restrict モードはトラフィックブロックに加えてログ出力やカウンタ加算を行います（protect モードはログ出力なし、shutdown はポート遮断）。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-sec-07",
    cert: "ccna",
    category: "セキュリティ基礎",
    text: "DHCP スヌーピング (DHCP Snooping) 機能において、正規の DHCP サーバーが接続されているポートに対して設定すべき信頼状態はどれか？",
    options: ["trusted (トラステッド) ポート", "untrusted (アントラステッド) ポート", "promiscuous (プロミスキャス) ポート", "monitor (モニター) ポート"],
    correctIndex: 0,
    explanation: "DHCPスヌーピングでは、DHCP OfferやAckを返信可能な正規サーバー側のポートを「ip dhcp snooping trust」として Trusted に設定します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-sec-08",
    cert: "ccna",
    category: "セキュリティ基礎",
    text: "DAI (Dynamic ARP Inspection) はどのデータベースを参照して、不正な ARP パケット（ARPスプーフィング攻撃など）を検出・破棄するか？",
    options: ["DHCP スヌーピングバインディングデータベース", "MAC アドレステーブル", "ルーティングテーブル", "VLAN データベース"],
    correctIndex: 0,
    explanation: "DAI は DHCP スヌーピングによって構築された「IP - MAC - VLAN - ポート」の正規バインディング情報と照合して不正ARPを排除します。",
    difficulty: "advanced",
  },
  {
    questionId: "q-ccna-sec-09",
    cert: "ccna",
    category: "セキュリティ基礎",
    text: "Cisco 拡張 ACL (アクセス制御リスト) を評価する際の特徴として「正しい」ものはどれか？",
    options: ["先頭の条件行から上から下へと順に評価され、一致した行があった瞬間に処理が確定する", "すべての行を最後まで評価し、最も厳しい条件を適用する", "許可行のみを先に評価し、その後で拒否行を評価する", "必ずインターフェースの受信側 (in) にしか適用できない"],
    correctIndex: 0,
    explanation: "ACL はトップダウンで上から行順に評価され、最初に条件に合致した時点で評価を終了します。また末尾には暗黙の deny all が存在します。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-sec-10",
    cert: "ccna",
    category: "セキュリティ基礎",
    text: "WPA3 で採用され、従来の事前共有鍵（WPA2-PSK）の辞書攻撃への脆弱性を克服した、安全なピア間ハンドシェイク認証プロトコルはどれか？",
    options: ["SAE (Simultaneous Authentication of Equals)", "TKIP (Temporal Key Integrity Protocol)", "CCMP (Counter Mode with CBC-MAC)", "EAP-TLS"],
    correctIndex: 0,
    explanation: "WPA3-Personal では SAE（通称 Dragonflies ハンドシェイク）が導入され、オフライン辞書攻撃を防ぐ強固な鍵交換を実現しています。",
    difficulty: "advanced",
  },
  {
    questionId: "q-ccna-auto-06",
    cert: "ccna",
    category: "自動化とプログラマビリティ",
    text: "JSON 形式のデータ表記において、「配列 (Array)」を表す括弧のペアと「オブジェクト (Object)」を表す括弧のペアの組み合わせはどれか？",
    options: ["配列は [ ] (角括弧)、オブジェクトは { } (波括弧)", "配列は { } (波括弧)、オブジェクトは [ ] (角括弧)", "配列は ( ) (丸括弧)、オブジェクトは < > (山括弧)", "配列は << >>、オブジェクトは { }"],
    correctIndex: 0,
    explanation: "JSONでは複数要素の並び（配列）は角括弧 [ 'a', 'b' ]、キーと値のペア群（オブジェクト）は波括弧 { 'key': 'value' } を使います。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-auto-07",
    cert: "ccna",
    category: "自動化とプログラマビリティ",
    text: "REST API において、サーバーに「新しいリソースを正常に作成した」ことを示す HTTP ステータスコードはどれか？",
    options: ["201 Created", "200 OK", "204 No Content", "202 Accepted"],
    correctIndex: 0,
    explanation: "HTTPステータスコードにおいて 201 Created は新規リソースの作成完了を、200 OK は通常の正常完了を表します。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-auto-08",
    cert: "ccna",
    category: "自動化とプログラマビリティ",
    text: "構成管理ツール「Ansible」の大きな特徴として正しいものはどれか？",
    options: ["管理対象ノードに専用エージェントのインストールが不要で、SSH（またはWinRM）経由で実行される", "必ずクライアント側に Ruby で書かれた Puppet エージェントの導入が必要である", "構成ファイル（Playbook）の記述には XML フォーマットのみを採用している", "Cisco ネットワーク機器では一切利用できない"],
    correctIndex: 0,
    explanation: "Ansible はエージェントレス構造が最大の特長であり、YAML 形式で書かれた Playbook を SSH 経由で対象ノードに実行させます。",
    difficulty: "beginner",
  },
  {
    questionId: "q-ccna-auto-09",
    cert: "ccna",
    category: "自動化とプログラマビリティ",
    text: "Cisco DNA Center (Catalyst Center) による「インテントベース・ネットワーク（IBN）」の主要な役割・メリットはどれか？",
    options: ["ビジネスの「意図 (Intent)」に基づく自動化ポリシー適用とアシュアランス（品質保証・分析）を一元提供する", "物理ルーターを廃止してすべての通信を Bluetooth で置き換える", "従来 CLI による各機器ごとの手動設定のみをサポートする", "OSPF ルーティングプロトコルの AD 値を 0 に固定する"],
    correctIndex: 0,
    explanation: "DNA Center はビジネス目標や要件（Intent）から自動的にネットワーク構成を生成し、AI・分析による健全性の監視を提供します。",
    difficulty: "intermediate",
  },
  {
    questionId: "q-ccna-auto-10",
    cert: "ccna",
    category: "自動化とプログラマビリティ",
    text: "Python でネットワーク機器との SSH セッションを開始し、CLI コマンドを実行して出力を取得するために最も広く利用されている特化型ライブラリはどれか？",
    options: ["Netmiko", "BeautifulSoup", "Pygame", "Matplotlib"],
    correctIndex: 0,
    explanation: "Netmiko は Paramiko を基盤にして Cisco や他社製ネットワーク機器の SSH 接続・CLI プロンプト処理を簡単に行えるようにした定番ライブラリです。",
    difficulty: "advanced",
  },
];
