# ─────────────────────────────────────────────────────────────────
# Dockerfile for LPIC×CCNA 学習室 (Next.js 16 / standalone output)
# Multi-stage build: builder → runner
# Target: AWS App Runner (or any OCI-compliant runtime)
# ─────────────────────────────────────────────────────────────────

# ── Stage 1: Dependencies ─────────────────────────────────────────
FROM node:20-alpine AS deps
WORKDIR /app

# Install only production deps first for better layer caching
COPY package.json package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts

# ── Stage 2: Builder ──────────────────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app

# Copy ALL deps (including devDependencies) for the build
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

COPY . .

# Build-time env (public vars only – secrets are injected at runtime)
# ARGs here are only for NEXT_PUBLIC_ variables if needed
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

RUN npm run build

# ── Stage 3: Runner ───────────────────────────────────────────────
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# Port that App Runner / CloudFront expects
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Non-root user for security
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# Copy standalone bundle (generated by next.config.ts: output: 'standalone')
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs

EXPOSE 3000

# Health-check for App Runner
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -qO- http://localhost:3000/api/health || exit 1

CMD ["node", "server.js"]
